//! `rust` library/module emit — `LibraryClass` consumer +
//! Module-mode entry points.
//!
//! Phase 2.1 scope: Module-mode `emit_module` for free-function
//! runtime files (inflector). Library-mode `emit_library_class`
//! comes in Phase 2.2 (HWIA) when struct + impl emit lands.

use std::fmt::Write;

use super::method::{emit_instance_method, emit_module_method};
use super::ty::rust_ty;
use crate::dialect::{LibraryClass, MethodDef, MethodReceiver};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ty::Ty;

/// Module mode — flat list of `def self.*` helpers (e.g.
/// `inflector.rb`'s `Inflector.pluralize`). Each method emits as a
/// top-level `pub fn`. The output file IS the namespace at the
/// Rust module level (`src/inflector.rs` → `crate::inflector`); no
/// extra `mod NAME { ... }` wrapper needed.
///
/// Mirrors `crystal::emit_module` in role; differs in that crystal
/// requires explicit `module X ... end` wrapping while rust uses
/// the file-as-module convention.
///
/// Module-mode entries bypass the `runtime_loader::transpile_entry`
/// `transform` closure that Library-mode runs (the closure is the
/// hook `rust.rs` uses for `str_color` on Library-mode classes).
/// Apply the same `str_color` pass here so Module-mode methods
/// (router.rb, view_helpers.rb's free functions, etc.) get the
/// same ownership annotations before emit.
pub fn emit_module(methods: &[MethodDef]) -> Result<String, String> {
    if methods.is_empty() {
        return Ok(String::new());
    }
    let mut colored: Vec<MethodDef> = methods.to_vec();
    let registry = crate::emit::rust::decide::str_color::build_registry_from_methods(&colored);
    for m in colored.iter_mut() {
        crate::emit::rust::decide::str_color::color_method(m, &registry);
    }
    // Run the rest of the decide pass (parens, last-use / clone-at)
    // on a single-class wrapper. Mirrors the multi-class call sites
    // in `rust.rs::emit`.
    let mut wrap = vec![crate::dialect::LibraryClass {
        name: crate::ident::ClassId(crate::ident::Symbol::from("__emit_module__")),
        is_module: false,
        parent: None,
        parent_span: Default::default(),
        includes: Vec::new(),
        methods: std::mem::take(&mut colored),
        nullable_columns: Vec::new(),
        origin: None,
        constants: Vec::new(),
        unknown_calls: Vec::new(),
        class_ivar_initializers: Vec::new(),
    }];
    super::decide::decide_classes(&mut wrap);
    colored = wrap.into_iter().next().unwrap().methods;
    let mut out = String::new();
    writeln!(out, "// Generated by Roundhouse (rust2).").unwrap();
    writeln!(out).unwrap();
    let mut first = true;
    for m in &colored {
        if !first {
            writeln!(out).unwrap();
        }
        first = false;
        out.push_str(&emit_module_method(m)?);
    }
    Ok(out)
}

/// Library mode — `class Foo ... end` → `pub struct Foo { ... }` +
/// `impl Foo { ... }`. Phase 2.2 lands the scaffold:
///
/// * Ivars are collected from method bodies and emitted as private
///   struct fields. Type comes from each ivar's first observed
///   assignment in the analyzed IR (the body-typer fills `e.ty`);
///   untyped ivars fall back to `serde_json::Value` via `rust_ty`.
/// * Each instance method emits as `pub fn name(&self, ...)` or
///   `pub fn name(&mut self, ...)`. The mutability heuristic walks
///   the body for `@ivar = ...` (LValue::Ivar) or `self[k] = v`
///   (LValue::Index recv=SelfRef) and picks `&mut self` if it sees
///   either.
/// * `def initialize` becomes `pub fn new(...) -> Self`; the
///   construction body is the user's `initialize` body with a final
///   `Self { fields }` return expression.
///
/// Subsequent commits drive the per-ExprNode body emit until the
/// produced Rust is `cargo check`-clean.
pub fn emit_library_class(class: &LibraryClass) -> Result<String, String> {
    emit_library_class_with_options(class, false, false)
}

pub(super) fn emit_app_library_class(
    source_class: &LibraryClass,
    is_current_attributes: bool,
) -> Result<String, String> {
    emit_library_class_with_options(source_class, is_current_attributes, true)
}

pub(super) fn emit_library_class_with_constants(
    source_class: &LibraryClass,
) -> Result<String, String> {
    emit_library_class_with_options(source_class, false, true)
}

fn emit_library_class_with_options(
    source_class: &LibraryClass,
    is_current_attributes: bool,
    emit_constants: bool,
) -> Result<String, String> {
    // CurrentAttributes exposes its instance methods through generated
    // class-level forwarders. Rust cannot have an inherent associated
    // function and an instance method with the same name, so retain the
    // stateful implementation under a private, distinct name and route
    // the generated forwarders to it. This is intentionally scoped to
    // classes identified by ingest metadata, not inferred from names.
    let class = if is_current_attributes {
        let mut class = source_class.clone();
        let instance_names: std::collections::HashSet<String> = class
            .methods
            .iter()
            .filter(|m| matches!(m.receiver, MethodReceiver::Instance))
            .map(|m| m.name.as_str().to_string())
            .collect();
        for method in &mut class.methods {
            if method.receiver == MethodReceiver::Instance {
                method.name =
                    crate::ident::Symbol::from(current_instance_method_name(method.name.as_str()));
            }
            rewrite_current_forwarder_calls(&mut method.body, &instance_names, &class.name);
        }
        class
    } else {
        source_class.clone()
    };
    emit_library_class_inner(&class, is_current_attributes, emit_constants)
}

fn emit_library_class_inner(
    class: &LibraryClass,
    is_current_attributes: bool,
    emit_constants: bool,
) -> Result<String, String> {
    // Strip the namespace prefix (`ActiveSupport::HashWithIndifferentAccess`
    // → `HashWithIndifferentAccess`). Rust uses file-as-module, so the
    // namespace is carried by the file path, not the struct name.
    let name = class
        .name
        .0
        .as_str()
        .rsplit("::")
        .next()
        .unwrap_or(class.name.0.as_str())
        .to_string();

    let mut ivars = collect_ivar_types(&class.methods);
    if is_current_attributes {
        // CurrentAttributes readers are nil before the first request-scoped
        // write, even when every observed setter call passes a value. Keep
        // the backing slot in the reader's nullable shape without widening
        // the setter's input type.
        for method in &class.methods {
            if method.receiver != MethodReceiver::Instance {
                continue;
            }
            let ExprNode::Ivar { name } = &*method.body.node else {
                continue;
            };
            let Some(Ty::Fn { ret, .. }) = method.signature.as_ref() else {
                continue;
            };
            let Ty::Union { variants } = &**ret else {
                continue;
            };
            if !variants.iter().any(|variant| matches!(variant, Ty::Nil)) {
                continue;
            }
            if let Some((_, ty)) = ivars.iter_mut().find(|(field, _)| field == name.as_str()) {
                *ty = ret.as_ref().clone();
            }
        }
    }

    // Module-singleton classes (Ruby `class << self; attr_accessor
    // :slot; end` inside a `module X`) have only class methods —
    // their "ivars" are module-level state, not per-instance fields.
    // Rust analog: unit struct + per-slot `Mutex<Option<T>>` statics.
    // Detection: every method has Class receiver and the class isn't
    // empty (the empty-class case is just a marker, e.g. `module X;
    // end`, and falls through to the regular struct emit shape).
    let is_module_singleton = !class.methods.is_empty()
        && class
            .methods
            .iter()
            .all(|m| matches!(m.receiver, MethodReceiver::Class));
    if is_module_singleton {
        return emit_module_singleton(&name, &ivars, class, emit_constants);
    }

    // Pre-pass: identify methods whose body never reads `self` or
    // any `@ivar`. Those are static-safe — emit as `pub fn name(...)`
    // (no `self` receiver) so they're callable from `new` before an
    // instance exists. HWIA's `normalize_value` is the canonical
    // case: pure value-transformation, no instance state. The
    // companion call-site rewrite in `expr.rs::emit_send` routes
    // `self.method(args)` for these methods to `Self::method(args)`.
    let instance_method_names: std::collections::HashSet<String> = class
        .methods
        .iter()
        .filter(|m| matches!(m.receiver, MethodReceiver::Instance))
        .map(|m| m.name.as_str().to_string())
        .collect();
    let eligible_static_methods: Vec<&MethodDef> = class
        .methods
        .iter()
        .filter(|m| {
            matches!(m.receiver, MethodReceiver::Instance)
                && !is_current_attributes
                && m.name.as_str() != "initialize"
                // Only methods with no receiver/state or sibling-method
                // dispatch can be lifted. Sibling calls remain dynamic so
                // instance APIs and overrides keep their Ruby behavior.
                && !method_reads_self(
                    &m.body,
                    &instance_method_names,
                    &std::collections::HashSet::new(),
                )
                // Abstract-stub bodies (just `raise NotImplementedError`)
                // are the per-class contract markers. They don't read
                // self by construction, but per-model subclasses override
                // them — and callers reach the overrides through
                // instance dispatch (`record.dom_prefix()`). Classify
                // those as `&self` methods so the call site resolves.
                && !is_raise_only_body(&m.body)
                // The OVERRIDES of those markers get the same shape by
                // NAME: a non-STI model's `dom_prefix` body is a bare
                // string literal (reads no self), but the broadcast
                // lowerings call it through a typed receiver
                // (`parent.dom_prefix()`), and a static override of an
                // instance contract strands that call site.
                // Literal controller identity methods still implement an instance API.
                && !matches!(
                    m.name.as_str(),
                    "dom_prefix"
                        | "dom_record_key"
                        | "to_param"
                        | "controller_name"
                        | "controller_path"
                )
        })
        .collect();
    let mut static_method_names: std::collections::HashSet<String> = eligible_static_methods
        .iter()
        .map(|method| method.name.as_str().to_string())
        .collect();
    loop {
        let non_static_instance_methods: std::collections::HashSet<String> = instance_method_names
            .difference(&static_method_names)
            .cloned()
            .collect();
        let next: std::collections::HashSet<String> = eligible_static_methods
            .iter()
            .filter(|method| {
                !method_reads_self(
                    &method.body,
                    &instance_method_names,
                    &non_static_instance_methods,
                )
            })
            .map(|method| method.name.as_str().to_string())
            .collect();
        if next == static_method_names {
            break;
        }
        static_method_names = next;
    }

    // `mutates_self` flag is filled by `analyze::mutates_self::propagate`
    // alongside the str_color pass in `emit/rust.rs`'s transform
    // closure. Build the per-class mutating-name set from the flags
    // for the `static_method_names` exclusion check + the existing
    // call-site method-mutates logic that the body emit consults.
    let mutating_methods: std::collections::HashSet<String> = class
        .methods
        .iter()
        .filter(|m| m.mutates_self)
        .map(|m| m.name.as_str().to_string())
        .collect();

    let mut out = String::new();

    if emit_constants {
        emit_class_constants(&mut out, class);
    }

    // CurrentAttributes is request-local state, not an entry in an
    // untyped Thread hash. Class-level accessors borrow this typed slot.
    if is_current_attributes {
        writeln!(out, "thread_local! {{").unwrap();
        writeln!(out, "    static __CURRENT_ATTRIBUTES_{name}: std::cell::RefCell<Option<{name}>> = const {{ std::cell::RefCell::new(None) }};").unwrap();
        writeln!(out, "}}\n").unwrap();
    }

    // Struct declaration. Derive `Clone` because Ruby semantics treat
    // model instances as freely cloneable (every assignment and
    // method-call argument-pass implicitly copies a reference, and
    // the framework Ruby's `attr_reader` getters and `.dup` patterns
    // expect to hand out independent copies). Each ivar type must
    // itself be Clone — every type rust emits today (i64, String,
    // bool, Vec<T: Clone>, HashMap<String, serde_json::Value>,
    // Option<T: Clone>, Class names → Clone'd) satisfies that.
    //
    // Also derive `Default` so axum-wrapper-emitted code can
    // `<Controller>::default()`-construct a controller with empty
    // params + flash + zeroed model ivars (wedge 2c). Every Rust
    // primitive type (i64/bool/f64/String) is Default; container
    // types (Vec/HashMap/Option) too; and the lowerer-emitted
    // model classes — Article, Comment, Row holders, Params
    // resources — are themselves marked `#[derive(Default)]` by
    // this same path, so the derive cascades through cross-model
    // ivar references. If a future non-Default ivar lands, this
    // derive will fail at compile time and we'll need a per-class
    // override.
    writeln!(out, "#[derive(Clone, Default)]").unwrap();
    writeln!(out, "pub struct {name} {{").unwrap();
    // Fields are `pub` so legacy-emit-style controller test bodies
    // (`@article.title`, `Article.last.id`) — which use field
    // access syntax rather than getter method calls — resolve
    // against the same struct. The lowerer-emitted instance
    // methods (`title(&self) -> String { self.title.clone() }`)
    // still work alongside; Rust disambiguates field vs method
    // by trailing parens at the call site.
    for (fname, ty) in &ivars {
        let field = super::expr::util::escape_rust_keyword(fname);
        writeln!(out, "    pub {field}: {},", rust_ty(ty)).unwrap();
    }
    out.push_str("}\n\n");

    // Impl block. Each method renders independently; `initialize`
    // routes through the constructor variant of `emit_instance_method`.
    // `def self.X` class methods emit as `pub fn name(...)` (no
    // receiver) — Rust's free-function-in-impl form. Callers reach
    // them via `Type::name(...)`, same dispatch path static-safe
    // instance methods use.
    writeln!(out, "impl {name} {{").unwrap();
    let mut first = true;
    if is_current_attributes
        && !class
            .methods
            .iter()
            .any(|method| method.name.as_str() == "initialize")
    {
        writeln!(out, "    pub fn new() -> Self {{ Self::default() }}\n").unwrap();
    }
    // Make this class's ivar → field-type table available to
    // `emit_assign` (via thread-local) so RHS values can be coerced
    // when their Ty doesn't match the declared field type — most
    // commonly `self.body = ""` where field is `String` and `""` is
    // `&str`. Empty outside class-body scope; scoped per-class to
    // prevent bleeding between siblings.
    let ivar_type_map: std::collections::HashMap<String, Ty> = ivars.iter().cloned().collect();
    let class_method_param_tys = collect_class_method_param_tys(&class.methods);
    let body_result = super::expr::with_class_method_param_tys(class_method_param_tys, || {
        super::expr::with_ivar_types(ivar_type_map, || {
            super::expr::with_instance_methods(instance_method_names.clone(), || {
                super::expr::with_static_methods(static_method_names.clone(), || {
                    for m in &class.methods {
                        if !first {
                            writeln!(out).unwrap();
                        }
                        first = false;
                        let body = if is_current_attributes {
                            emit_current_attributes_method(m, &class.methods, &name, &ivars)?
                        } else {
                            match m.receiver {
                                MethodReceiver::Class => {
                                    // `def self.X` → `pub fn X(...)` with no receiver.
                                    // Module-style call from within the impl block.
                                    super::method::emit_module_method_for_class(m, &name)?
                                }
                                MethodReceiver::Instance => {
                                    let is_static = static_method_names.contains(m.name.as_str());
                                    let mutates = mutating_methods.contains(m.name.as_str());
                                    emit_instance_method(m, mutates, is_static, &name, &ivars)?
                                }
                            }
                        };
                        for line in body.lines() {
                            if line.is_empty() {
                                writeln!(out).unwrap();
                            } else {
                                writeln!(out, "    {line}").unwrap();
                            }
                        }
                    }
                    Ok::<(), String>(())
                })
            })
        })
    });
    body_result?;
    if name == "Base" && class.methods.iter().any(|m| m.name.as_str() == "render") {
        // 2-arg `self.render(body, opts)` rewrites to `render_with`.
        // Controller subclasses get that shim from rust.rs; Base
        // itself must unpack opts onto its 4-arg `render`.
        writeln!(out).unwrap();
        writeln!(
            out,
            "    pub fn render_with(&mut self, content: &str, opts: std::collections::HashMap<String, serde_json::Value>) {{"
        )
        .unwrap();
        writeln!(
            out,
            "        let status = opts.get(\"status\").and_then(|v| v.as_str()).unwrap_or(\"ok\");"
        )
        .unwrap();
        writeln!(out, "        self.render(content, status, None, None);").unwrap();
        writeln!(out, "    }}").unwrap();
    }
    out.push_str("}\n");
    Ok(out)
}

fn current_instance_method_name(name: &str) -> String {
    let rust_name = if let Some(base) = name.strip_suffix('=') {
        format!("set_{base}")
    } else {
        super::expr::sanitize_ident(name)
    };
    format!("__current_instance_{rust_name}")
}

fn emit_current_attributes_method(
    method: &MethodDef,
    methods: &[MethodDef],
    class_name: &str,
    ivars: &[(String, Ty)],
) -> Result<String, String> {
    if method.receiver != MethodReceiver::Class {
        let mut method = method.clone();
        if method.name.as_str().starts_with("__current_instance_set_")
            && let ExprNode::Assign {
                target: crate::expr::LValue::Ivar { .. },
                value,
            } = &*method.body.node
            && matches!(&*value.node, ExprNode::Var { name, .. } if method.params.first().is_some_and(|param| param.name == *name))
        {
            let ExprNode::Assign { target, value } = &*method.body.node else {
                unreachable!();
            };
            let mut cloned_value = Expr::new(
                value.span,
                ExprNode::Send {
                    recv: Some(value.clone()),
                    method: crate::ident::Symbol::from("clone"),
                    args: Vec::new(),
                    block: None,
                    parenthesized: false,
                },
            );
            cloned_value.ty.clone_from(&value.ty);
            let assignment = Expr::new(
                method.body.span,
                ExprNode::Assign {
                    target: target.clone(),
                    value: cloned_value,
                },
            );
            method.body = Expr::new(
                method.body.span,
                ExprNode::Seq {
                    exprs: vec![assignment, value.clone()],
                },
            );
        }
        let mut rendered = super::method::emit_instance_method(
            &method,
            method.mutates_self,
            false,
            class_name,
            ivars,
        )?;
        if let Some(base) = method.name.as_str().strip_prefix("__current_instance_set_") {
            if let Some((_, ty)) = ivars.iter().find(|(field, _)| field == base) {
                rendered = rendered.replace("value: ()", &format!("value: {}", rust_ty(ty)));
            }
        }
        return Ok(rendered);
    }

    let name = method.name.as_str();
    if name == "instance" {
        return Ok(format!(
            "pub fn instance() -> {class_name} {{\n        __CURRENT_ATTRIBUTES_{class_name}.with(|slot| {{\n            if slot.borrow().is_none() {{ *slot.borrow_mut() = Some({class_name}::new()); }}\n            slot.borrow().as_ref().unwrap().clone()\n        }})\n    }}"
        ));
    }
    if name == "reset" {
        return Ok(format!(
            "pub fn reset() {{\n        __CURRENT_ATTRIBUTES_{class_name}.with(|slot| *slot.borrow_mut() = Some({class_name}::new()));\n    }}"
        ));
    }

    // The generated Rails class API consists of one class method for each
    // instance method. Retain the inferred signature, but route it to the
    // request-local instance instead of cloning Current::instance() (which
    // would make writes disappear).
    let target = methods.iter().find(|candidate| {
        candidate.receiver == MethodReceiver::Instance
            && (candidate.name.as_str() == current_instance_method_name(name)
                || name
                    .strip_prefix("set_")
                    .map(|base| {
                        candidate.name.as_str() == current_instance_method_name(&format!("{base}="))
                    })
                    .unwrap_or(false))
    });
    let Some(target) = target else {
        return super::method::emit_module_method(method);
    };
    let instance_name = target.name.as_str().to_string();
    let rendered = super::method::emit_module_method(method)?;
    let (header, _) = rendered
        .split_once(" {\n")
        .ok_or_else(|| format!("could not find Rust function body for Current::{name}"))?;
    let mut out = format!(
        "{header} {{\n        __CURRENT_ATTRIBUTES_{class_name}.with(|slot| {{\n            if slot.borrow().is_none() {{ *slot.borrow_mut() = Some({class_name}::new()); }}\n"
    );
    let is_writer = name.starts_with("set_")
        || instance_name.starts_with("__current_instance_set_");
    if is_writer {
        if let Some(base) = name.strip_prefix("set_") {
            if let Some((_, ty)) = ivars.iter().find(|(field, _)| field == base) {
                out = out.replace("value: ()", &format!("value: {}", rust_ty(ty)));
            }
        }
    }
    let call = if is_writer {
        format!("slot.borrow_mut().as_mut().unwrap().{instance_name}(value);")
    } else {
        format!("slot.borrow().as_ref().unwrap().{instance_name}()")
    };
    writeln!(out, "            {call}").unwrap();
    out.push_str("        })\n    }");
    Ok(out)
}

fn rewrite_current_forwarder_calls(
    expr: &mut Expr,
    instance_names: &std::collections::HashSet<String>,
    current_class: &crate::ident::ClassId,
) {
    if let ExprNode::Send { recv, method, .. } = &mut *expr.node {
        let is_current_instance = match recv.as_ref() {
            None => true,
            Some(receiver) if matches!(&*receiver.node, ExprNode::SelfRef) => true,
            Some(receiver) => matches!(
                &*receiver.node,
                ExprNode::Send {
                    recv: Some(class),
                    method: instance,
                    args,
                    ..
                } if instance.as_str() == "instance"
                    && args.is_empty()
                    && matches!(&*class.node, ExprNode::Const { path }
                        if path.last().map(|name| name.as_str())
                            == current_class.0.as_str().rsplit("::").next())
            ),
        };
        if is_current_instance && instance_names.contains(method.as_str()) {
            *method = crate::ident::Symbol::from(current_instance_method_name(method.as_str()));
        }
    }
    expr.node.for_each_child_mut(&mut |child| {
        rewrite_current_forwarder_calls(child, instance_names, current_class)
    });
}

#[cfg(test)]
mod current_attributes_emit_tests {
    use super::emit_app_library_class;

    #[test]
    fn current_attributes_forwards_class_apis_to_distinct_stateful_methods() {
        let classes = crate::ingest::ingest_library_classes(
            b"class Current\n  def user\n    @user\n  end\n  def user=(value)\n    @user = value\n  end\n  def account\n    Account.first\n  end\n  def self.user\n    Current.instance.user\n  end\n  def self.set_user(value)\n    Current.instance.user = value\n  end\n  def self.account\n    Current.instance.account\n  end\n  def self.user_from(session)\n    session.user\n  end\nend\n",
            "current.rb",
        )
        .expect("Current class ingests");
        let emitted =
            crate::emit::rust::expr::with_emit_ctx(crate::emit::rust::EmitCtx::default(), || {
                emit_app_library_class(&classes[0], true).expect("emits")
            });

        assert!(
            emitted.contains("pub fn user()"),
            "class API is static:\n{emitted}"
        );
        assert!(
            emitted.contains("pub fn set_user("),
            "writer API is static:\n{emitted}"
        );
        assert!(
            emitted.contains("pub fn __current_instance_user(&self)"),
            "instance state accessor remains stateful:\n{emitted}"
        );
        assert!(
            emitted.contains("__CURRENT_ATTRIBUTES_Current.with(|slot|"),
            "class forwarders use request-local state:\n{emitted}"
        );
        assert!(
            emitted.contains("thread_local!"),
            "state is thread-local:\n{emitted}"
        );
        assert!(
            emitted.contains("pub fn new() -> Self"),
            "Current has a constructor for its default state:\n{emitted}"
        );
        assert!(
            emitted.contains("borrow_mut().as_mut().unwrap().__current_instance_set_user(value)"),
            "writer updates the stored instance:\n{emitted}"
        );
        assert!(
            emitted.contains("pub fn __current_instance_account(&self)"),
            "custom instance method is retained:\n{emitted}"
        );
        assert!(
            emitted.contains("session.user()")
                && !emitted.contains("session.__current_instance_user()"),
            "unrelated receivers must not be redirected to Current's stored state:\n{emitted}"
        );
        assert!(
            !emitted.contains("pub fn user(&self)"),
            "associated and instance APIs must not collide:\n{emitted}"
        );
    }
}

/// Module singletons whose state is *per-request render state*, not
/// process-wide configuration. Their ivar slots emit as `thread_local!`
/// `RefCell<Option<T>>` instead of a global `Mutex<Option<T>>`.
///
/// Why: `ViewHelpers`' content_for/yield slot store is reset and
/// repopulated on every request. Behind a process-global mutex, every
/// concurrent render serializes on one lock — profiled at c=64 as
/// ~46% of thread-time blocked in mutex wait on the no-DB
/// `/articles/new` endpoint (roundhouse#32); switching to
/// thread-locals measured +24% throughput. Thread-locals are correct
/// here because a request's render runs synchronously inside one
/// handler poll (controller action → views → layout, no `.await`
/// between `set_yield` and `get_yield`), so the state never needs to
/// cross threads. This mirrors Rails' own per-thread scoping of view
/// rendering state (and the hand-written `runtime/rust/view_helpers.rs`,
/// which used `thread_local!` before the framework runtime moved to
/// transpiled Ruby).
///
/// Config-like singletons (`ActiveRecord`'s ADAPTER: set once at boot
/// from the main thread, read from every worker) must stay global, so
/// global-Mutex remains the default and this list is opt-in. The
/// durable fix — threading an `ActionView::Slots` value object
/// per-request — is tracked in runtime/ruby/action_view/view_helpers.rb's
/// header comment; this list is the call surface's interim shape.
const REQUEST_SCOPED_SINGLETONS: &[&str] = &["ViewHelpers"];

fn is_request_scoped_singleton(name: &str) -> bool {
    REQUEST_SCOPED_SINGLETONS.contains(&name)
}

/// Emit a Ruby `module X; class << self; attr_accessor :slot; end;
/// end` class as a Rust unit struct + per-slot `Mutex<Option<T>>`
/// statics (or `thread_local!` `RefCell<Option<T>>` for
/// request-scoped singletons — see `REQUEST_SCOPED_SINGLETONS`).
/// The transpiled `attr_accessor` getter/setter pair routes
/// through the static slot (see `expr.rs::in_module_singleton`).
///
/// Produces:
///
/// ```text
/// pub struct ActiveRecord;
///
/// static ADAPTER: std::sync::Mutex<Option<Value>> =
///     std::sync::Mutex::new(None);
///
/// impl ActiveRecord {
///     pub fn adapter() -> Value { ... }
///     pub fn set_adapter(value: Value) { ... }
/// }
/// ```
fn emit_module_singleton(
    name: &str,
    ivars: &[(String, Ty)],
    class: &LibraryClass,
    emit_constants: bool,
) -> Result<String, String> {
    let thread_local = is_request_scoped_singleton(name);
    let mut out = String::new();
    if emit_constants {
        emit_class_constants(&mut out, class);
    }
    // Unit struct — no per-instance fields. Callers reach the slot
    // methods via `ActiveRecord::adapter()` / `ActiveRecord::set_adapter(v)`.
    writeln!(out, "pub struct {name};\n").unwrap();
    // One slot static per ivar. Naming follows the SCREAMING_SNAKE
    // Rust static convention; trim_start_matches('_') handles
    // leading-underscore ivars. Request-scoped singletons get
    // `thread_local!` `RefCell<Option<T>>` slots; everything else a
    // process-global `Mutex<Option<T>>`.
    if thread_local && !ivars.is_empty() {
        writeln!(out, "thread_local! {{").unwrap();
        for (fname, ty) in ivars {
            let slot = super::expr::module_singleton_slot_name(fname);
            writeln!(
                out,
                "    static {slot}: std::cell::RefCell<Option<{}>> = const {{ std::cell::RefCell::new(None) }};",
                rust_ty(ty),
            )
            .unwrap();
        }
        writeln!(out, "}}").unwrap();
    } else {
        for (fname, ty) in ivars {
            let slot = super::expr::module_singleton_slot_name(fname);
            writeln!(
                out,
                "static {slot}: std::sync::Mutex<Option<{}>> = std::sync::Mutex::new(None);",
                rust_ty(ty),
            )
            .unwrap();
        }
    }
    if !ivars.is_empty() {
        out.push('\n');
    }
    writeln!(out, "impl {name} {{").unwrap();
    let ivar_type_map: std::collections::HashMap<String, Ty> = ivars.iter().cloned().collect();
    let class_method_param_tys = collect_class_method_param_tys(&class.methods);
    let body_result = super::expr::with_class_method_param_tys(class_method_param_tys, || {
        super::expr::with_module_singleton(true, thread_local, || {
            super::expr::with_ivar_types(ivar_type_map, || {
                let mut first = true;
                for m in &class.methods {
                    if matches!(m.name.as_str(), "[]" | "[]=") {
                        continue;
                    }
                    if !first {
                        writeln!(out).unwrap();
                    }
                    first = false;
                    // Module-singleton methods are class methods by
                    // construction (detection in `emit_library_class`).
                    let body = super::method::emit_module_method_for_class(m, name)?;
                    for line in body.lines() {
                        if line.is_empty() {
                            writeln!(out).unwrap();
                        } else {
                            writeln!(out, "    {line}").unwrap();
                        }
                    }
                }
                Ok::<(), String>(())
            })
        })
    });
    body_result?;
    out.push_str("}\n");
    Ok(out)
}

/// Ruby class/module constant references emit as bare names, so their
/// definitions belong in the file-as-module scope shared by that owner.
fn emit_class_constants(out: &mut String, class: &LibraryClass) {
    for (name, value) in &class.constants {
        let constant = if constant_value_is_supported(value) {
            format_constant(name.as_str(), value)
        } else {
            format!("// TODO rust2 const: {} has a non-literal initializer", name.as_str())
        };
        writeln!(out, "{constant}").unwrap();
    }
    if !class.constants.is_empty() {
        out.push('\n');
    }
}

fn constant_value_is_supported(value: &Expr) -> bool {
    match &*value.node {
        ExprNode::Lit { .. } => true,
        ExprNode::Array { elements, .. } => elements.iter().all(constant_value_is_supported),
        ExprNode::Hash { entries, .. } => entries
            .iter()
            .all(|(key, value)| constant_value_is_supported(key) && constant_value_is_supported(value)),
        _ => false,
    }
}

/// `true` when the method body is a bare `raise X` call. The ingest
/// pipeline parses Ruby `raise NotImplementedError, "..."` as
/// `Send { recv: None, method: "raise", args: [...] }`, NOT as
/// `ExprNode::Raise` (which is unused in this codebase). Abstract-
/// contract stubs (the `raise NotImplementedError, "..."` convention
/// in `runtime/ruby/`) satisfy this — they're meant to be overridden,
/// and call sites reach the overrides through `record.method()`
/// instance dispatch. Classifying those as static would break that
/// dispatch path (associated-function call form only).
fn is_raise_only_body(body: &Expr) -> bool {
    fn is_raise_send(e: &Expr) -> bool {
        matches!(
            &*e.node,
            ExprNode::Send { recv: None, method, .. } if method.as_str() == "raise"
        )
    }
    match &*body.node {
        ExprNode::Send {
            recv: None, method, ..
        } if method.as_str() == "raise" => true,
        ExprNode::Seq { exprs } if exprs.len() == 1 => is_raise_send(&exprs[0]),
        _ => false,
    }
}

/// Static-method probe: returns `true` when the method body references
/// `self` directly, reads/writes an ivar, or implicitly calls another
/// instance method/ivar reader. The pre-pass in `emit_library_class`
/// filters this down to methods that can be lifted to `pub fn name(...)`
/// (no `&self`).
fn method_reads_self(
    body: &Expr,
    instance_method_names: &std::collections::HashSet<String>,
    non_static_instance_methods: &std::collections::HashSet<String>,
) -> bool {
    fn walk(
        e: &Expr,
        instance_method_names: &std::collections::HashSet<String>,
        non_static_instance_methods: &std::collections::HashSet<String>,
    ) -> bool {
        match &*e.node {
            ExprNode::SelfRef | ExprNode::Ivar { .. } => true,
            ExprNode::Assign { target, value } => {
                if matches!(target, LValue::Ivar { .. }) {
                    return true;
                }
                if let LValue::Attr { recv, .. } | LValue::Index { recv, .. } = target {
                    if walk(recv, instance_method_names, non_static_instance_methods) {
                        return true;
                    }
                }
                walk(value, instance_method_names, non_static_instance_methods)
            }
            ExprNode::OpAssign { target, value, .. } => {
                let target_reads_self = match target {
                    LValue::Ivar { .. } => true,
                    LValue::Attr { recv, .. } => {
                        walk(recv, instance_method_names, non_static_instance_methods)
                    }
                    LValue::Index { recv, index } => {
                        walk(recv, instance_method_names, non_static_instance_methods)
                            || walk(index, instance_method_names, non_static_instance_methods)
                    }
                    LValue::Var { .. } | LValue::Const { .. } => false,
                };
                target_reads_self || walk(value, instance_method_names, non_static_instance_methods)
            }
            ExprNode::Seq { exprs } => exprs
                .iter()
                .any(|expr| walk(expr, instance_method_names, non_static_instance_methods)),
            ExprNode::If {
                cond,
                then_branch,
                else_branch,
            } => {
                walk(cond, instance_method_names, non_static_instance_methods)
                    || walk(
                        then_branch,
                        instance_method_names,
                        non_static_instance_methods,
                    )
                    || walk(
                        else_branch,
                        instance_method_names,
                        non_static_instance_methods,
                    )
            }
            ExprNode::While { cond, body, .. } => {
                walk(cond, instance_method_names, non_static_instance_methods)
                    || walk(body, instance_method_names, non_static_instance_methods)
            }
            ExprNode::Send {
                recv,
                method,
                args,
                block,
                ..
            } => {
                (recv.is_none() && instance_method_names.contains(method.as_str()))
                    || recv
                        .as_ref()
                        .map(|receiver| {
                            walk(receiver, instance_method_names, non_static_instance_methods)
                        })
                        .unwrap_or(false)
                    || args
                        .iter()
                        .any(|arg| walk(arg, instance_method_names, non_static_instance_methods))
                    || block
                        .as_ref()
                        .map(|b| walk(b, instance_method_names, non_static_instance_methods))
                        .unwrap_or(false)
            }
            ExprNode::Return { value } => {
                walk(value, instance_method_names, non_static_instance_methods)
            }
            ExprNode::StringInterp { parts } => parts.iter().any(|p| {
                if let crate::expr::InterpPart::Expr { expr } = p {
                    walk(expr, instance_method_names, non_static_instance_methods)
                } else {
                    false
                }
            }),
            ExprNode::Hash { entries, .. } => entries.iter().any(|(k, v)| {
                walk(k, instance_method_names, non_static_instance_methods)
                    || walk(v, instance_method_names, non_static_instance_methods)
            }),
            ExprNode::Array { elements, .. } => elements
                .iter()
                .any(|element| walk(element, instance_method_names, non_static_instance_methods)),
            // `||` / `&&` short-circuit expressions. Without this arm
            // a body like `label || @model_name` short-circuits the
            // self-detection: walk falls into the catch-all `_` arm
            // and returns false, so the method gets misclassified as
            // static-safe (FormBuilder.submit was the visible case —
            // 3 E0424 errors from the missing &self receiver).
            ExprNode::BoolOp { left, right, .. } => {
                walk(left, instance_method_names, non_static_instance_methods)
                    || walk(right, instance_method_names, non_static_instance_methods)
            }
            ExprNode::Lambda { body, .. } => {
                walk(body, instance_method_names, non_static_instance_methods)
            }
            ExprNode::Range { begin, end, .. } => {
                begin
                    .as_ref()
                    .map(|b| walk(b, instance_method_names, non_static_instance_methods))
                    .unwrap_or(false)
                    || end
                        .as_ref()
                        .map(|e| walk(e, instance_method_names, non_static_instance_methods))
                        .unwrap_or(false)
            }
            ExprNode::Yield { args } => args
                .iter()
                .any(|arg| walk(arg, instance_method_names, non_static_instance_methods)),
            // `case scrutinee; when …; body; end` — the per-arm
            // bodies + scrutinee can reach self via Ivar reads or
            // direct self-references. Lowerer-synthesized
            // `get_index` / `set_index` are the canonical case
            // (each arm reads/writes a `@col` Ivar); without this
            // arm both methods misclassified as static and emitted
            // without a `&self` receiver, blowing every Ivar
            // reference into E0424.
            ExprNode::Case { scrutinee, arms } => {
                walk(
                    scrutinee,
                    instance_method_names,
                    non_static_instance_methods,
                ) || arms.iter().any(|arm| {
                    walk(
                        &arm.body,
                        instance_method_names,
                        non_static_instance_methods,
                    )
                })
            }
            ExprNode::Cast { value, .. } => {
                walk(value, instance_method_names, non_static_instance_methods)
            }
            _ => false,
        }
    }
    walk(body, instance_method_names, non_static_instance_methods)
}

/// Walk all methods collecting `@ivar = …` assignments. Returns the
/// observed ivar set with each entry's inferred type (the analyzer
/// fills `Expr.ty` during typing; an unset `ty` falls back to
/// `Ty::Untyped` and renders as `serde_json::Value`).
/// Build a `method_name → positional_param_Tys` map for one class.
/// Block + keyword-rest params are filtered out so the call-site
/// positional index lines up with the resulting vector. Used by
/// `with_class_method_param_tys` to seed the callee-back-propagation
/// lookup in emit_send for `Self::method(args)` calls.
fn collect_class_method_param_tys(
    methods: &[MethodDef],
) -> std::collections::HashMap<String, Vec<Ty>> {
    use crate::ty::ParamKind;
    let mut out = std::collections::HashMap::new();
    for m in methods {
        let tys: Vec<Ty> = match m.signature.as_ref() {
            Some(Ty::Fn { params, .. }) => params
                .iter()
                .filter(|p| !matches!(p.kind, ParamKind::Block | ParamKind::KeywordRest))
                .map(|p| p.ty.clone())
                .collect(),
            _ => continue,
        };
        // Ruby `Class.new(args)` invokes `initialize(args)`; the IR
        // call site uses "new" but the body's MethodDef.name is
        // "initialize". Alias so `current_class_method_param_tys
        // ("new")` resolves at `Self::new(...)` / `Article::new(...)`
        // call sites (closes E0061 arity checks like the lowerer-
        // synthesized `from_row` calling `Article.new` zero-arg).
        if m.name.as_str() == "initialize" {
            out.insert("new".to_string(), tys.clone());
        }
        out.insert(m.name.as_str().to_string(), tys);
    }
    out
}

fn collect_ivar_types(methods: &[MethodDef]) -> Vec<(String, Ty)> {
    // Phase 1: walk every method body and record every Ty observed
    // assigning to each ivar — both direct `@x =` (Ivar lvalue) and
    // `self.x = ...` (Attr lvalue with SelfRef recv, which writes the
    // same backing field on the emitted struct). Preserve first-seen
    // order so the struct's field declaration order matches the
    // source's `def initialize` order.
    //
    // Two passes:
    //   pass 1 — walk_collect_ivars records writes (assignments)
    //   pass 2 — walk_collect_ivar_reads records reads ONLY for ivars
    //            with zero writes (inherited-from-parent surface like
    //            controller `@flash`/`@session`/`@params`, which AC::
    //            Base writes from outside the controller class body).
    // Without the read-pass, the struct emit omits inherited fields
    // and downstream `self.flash[:notice] = ...` hits E0609. With
    // read-pass that doesn't gate on no-writes, ivars already typed
    // by writes get widened by re-observation and break framework
    // runtime emit (e.g. `Base.flash` typed Option<Flash> mistakenly).
    let mut order: Vec<String> = Vec::new();
    let mut observed: std::collections::HashMap<String, Vec<Ty>> = std::collections::HashMap::new();
    for m in methods {
        walk_collect_ivars(&m.body, &mut order, &mut observed);
    }
    let written: std::collections::HashSet<String> = observed.keys().cloned().collect();
    for m in methods {
        walk_collect_ivar_reads(&m.body, &written, &mut order, &mut observed);
    }
    // Phase 2: unify each ivar's observed-type list into one Ty.
    // Rules:
    //   - {Nil, T, ...}            → Option<T> (T = first non-Nil)
    //   - {Nil}                    → Option<Untyped> (nil-only ivar,
    //                                widen to Option for setter shape)
    //   - {Hash<_,_>, Hash<K, V>}  → keep the widest (matches the
    //                                previous one-shot widening for
    //                                empty-literal seeded hashes)
    //   - {T}                      → T (single-type ivar)
    //   - {T1, T2, ...} mixed      → first observed (fallback)
    order
        .into_iter()
        .map(|name| {
            let tys = observed.remove(&name).unwrap_or_default();
            let unified = unify_ivar_tys(&tys);
            (name, unified)
        })
        .collect()
}

fn unify_ivar_tys(tys: &[Ty]) -> Ty {
    let has_nil = tys.iter().any(|t| matches!(t, Ty::Nil));
    let first_non_nil = tys.iter().find(|t| !matches!(t, Ty::Nil)).cloned();
    if has_nil {
        match first_non_nil {
            // Already nilable — a nullable column's slot type is
            // `Union{[T, Nil]}` at every write site, and observing a
            // bare `Nil` alongside it (the initialize seed) must not
            // wrap it again into `Option<Option<T>>`.
            Some(t @ Ty::Union { .. }) if matches!(&t, Ty::Union { variants } if variants.iter().any(|v| matches!(v, Ty::Nil))) => {
                t
            }
            Some(t) => Ty::Union {
                variants: vec![Ty::Nil, t],
            },
            // Nil-only ivar (e.g. `@location = nil` with no other
            // assignments visible in the class body) — widen to
            // Option<Untyped> so the setter side can assign any
            // value-typed payload without an E0308. Without widening
            // the field types as `()` and every other path fails.
            None => Ty::Union {
                variants: vec![Ty::Nil, Ty::Untyped],
            },
        }
    } else {
        // No Nil observed — pick the most informative concrete type.
        // For Hash, prefer the most-specified variant (Hash{K, V} with
        // concrete K/V over Hash{Untyped, Untyped}) — matches the
        // previous single-shot widening.
        tys.iter()
            .max_by_key(|t| match t {
                Ty::Hash { key, value } => {
                    let k = !matches!(**key, Ty::Untyped);
                    let v = !matches!(**value, Ty::Untyped);
                    (k as u8) + (v as u8)
                }
                // Empty `[]` seeds Array[Untyped]; a later `ivar << s`
                // (HeaderStore `@keys << key`) is Array[String]. Prefer
                // the concrete elem so rust emits `Vec<String>` not
                // `Vec<Value>`.
                Ty::Array { elem } => {
                    if matches!(elem.as_ref(), Ty::Untyped) {
                        1
                    } else {
                        2
                    }
                }
                _ => 0,
            })
            .cloned()
            .unwrap_or(Ty::Untyped)
    }
}

fn walk_collect_ivars(
    e: &Expr,
    order: &mut Vec<String>,
    observed: &mut std::collections::HashMap<String, Vec<Ty>>,
) {
    fn record(
        name: &str,
        ty: Ty,
        order: &mut Vec<String>,
        observed: &mut std::collections::HashMap<String, Vec<Ty>>,
    ) {
        let k = name.to_string();
        if !order.iter().any(|n| n == &k) {
            order.push(k.clone());
        }
        observed.entry(k).or_default().push(ty);
    }
    match &*e.node {
        ExprNode::Assign {
            target: LValue::Ivar { name },
            value,
        } => {
            let ty = value.ty.clone().unwrap_or(Ty::Untyped);
            record(name.as_str(), ty, order, observed);
            walk_collect_ivars(value, order, observed);
        }
        ExprNode::OpAssign {
            target: LValue::Ivar { name },
            op,
            value,
        } => {
            let ty = value.ty.clone().unwrap_or(Ty::Untyped);
            if matches!(op, crate::expr::OpAssignOp::OrOr) {
                record(
                    name.as_str(),
                    Ty::Nil,
                    order,
                    observed,
                );
            }
            record(name.as_str(), ty, order, observed);
            walk_collect_ivars(value, order, observed);
        }
        // `self.x = value` — Attr lvalue with SelfRef recv. Writes
        // the same backing field as `@x = value`. Without this, an
        // ivar assigned only as `@x = nil` in `initialize` and then
        // `self.x = path` in `redirect_to` would type as `()`,
        // mismatching every `self.x = path` site.
        ExprNode::Assign {
            target: LValue::Attr { recv, name },
            value,
        } if matches!(&*recv.node, ExprNode::SelfRef) => {
            let ty = value.ty.clone().unwrap_or(Ty::Untyped);
            record(name.as_str(), ty, order, observed);
            walk_collect_ivars(value, order, observed);
        }
        // `@ivar[k] = v` — Ruby parses as Send `[]=` on Ivar recv.
        // The empty-literal `@data = {}` types as `Hash<Untyped,
        // Untyped>` from analyzer inference; subsequent index-assigns
        // tell us the real key/value types. Only record a Hash
        // observation when the ivar's prior observations already
        // contain a Hash — otherwise `@flash[:notice] = "..."` (where
        // `@flash` is the typed `Flash` struct, not a HashMap) would
        // be misread as a Hash assignment and widen the ivar type
        // away from the concrete struct.
        ExprNode::Send {
            recv: Some(recv),
            method,
            args,
            ..
        } if method.as_str() == "<<" && args.len() == 1 => {
            if let ExprNode::Ivar { name } = &*recv.node {
                let elem = args[0].ty.clone().unwrap_or(Ty::Untyped);
                record(
                    name.as_str(),
                    Ty::Array {
                        elem: Box::new(elem),
                    },
                    order,
                    observed,
                );
            }
            walk_collect_ivars(recv, order, observed);
            args.iter()
                .for_each(|a| walk_collect_ivars(a, order, observed));
        }
        ExprNode::Send {
            recv: Some(recv),
            method,
            args,
            ..
        } if method.as_str() == "[]=" && args.len() == 2 => {
            if let ExprNode::Ivar { name } = &*recv.node {
                let key = name.as_str();
                let already_hash = observed
                    .get(key)
                    .map(|tys| tys.iter().any(|t| matches!(t, Ty::Hash { .. })))
                    .unwrap_or(false);
                if already_hash {
                    let k_ty = args[0].ty.clone().unwrap_or(Ty::Untyped);
                    let v_ty = args[1].ty.clone().unwrap_or(Ty::Untyped);
                    record(
                        key,
                        Ty::Hash {
                            key: Box::new(k_ty),
                            value: Box::new(v_ty),
                        },
                        order,
                        observed,
                    );
                }
            }
            walk_collect_ivars(recv, order, observed);
            args.iter()
                .for_each(|a| walk_collect_ivars(a, order, observed));
        }
        ExprNode::Seq { exprs } => exprs
            .iter()
            .for_each(|e| walk_collect_ivars(e, order, observed)),
        ExprNode::If {
            cond,
            then_branch,
            else_branch,
        } => {
            walk_collect_ivars(cond, order, observed);
            walk_collect_ivars(then_branch, order, observed);
            walk_collect_ivars(else_branch, order, observed);
        }
        ExprNode::Send {
            recv, args, block, ..
        } => {
            if let Some(r) = recv {
                walk_collect_ivars(r, order, observed);
            }
            args.iter()
                .for_each(|a| walk_collect_ivars(a, order, observed));
            if let Some(b) = block {
                walk_collect_ivars(b, order, observed);
            }
        }
        ExprNode::While { cond, body, .. } => {
            walk_collect_ivars(cond, order, observed);
            walk_collect_ivars(body, order, observed);
        }
        ExprNode::Return { value } => walk_collect_ivars(value, order, observed),
        _ => {}
    }
}

/// Second-pass walk that records ivar READS (not writes) — only for
/// ivars NOT already observed via writes. Closes the inherited-ivar
/// gap for controllers (`@flash`, `@session`, `@params` set by AC::
/// Base, read inside actions). Ivars with at least one write skip
/// this pass entirely — the write-based ty rules already cover them.
fn walk_collect_ivar_reads(
    e: &Expr,
    written: &std::collections::HashSet<String>,
    order: &mut Vec<String>,
    observed: &mut std::collections::HashMap<String, Vec<Ty>>,
) {
    fn record(
        name: &str,
        ty: Ty,
        order: &mut Vec<String>,
        observed: &mut std::collections::HashMap<String, Vec<Ty>>,
    ) {
        let k = name.to_string();
        if !order.iter().any(|n| n == &k) {
            order.push(k.clone());
        }
        observed.entry(k).or_default().push(ty);
    }
    match &*e.node {
        ExprNode::Ivar { name } => {
            let n = name.as_str();
            if !written.contains(n) {
                if let Some(ty) = e.ty.as_ref() {
                    if !ty.is_unknown() {
                        record(n, ty.clone(), order, observed);
                    }
                }
            }
        }
        ExprNode::Assign {
            target: LValue::Ivar { .. },
            value,
        } => {
            walk_collect_ivar_reads(value, written, order, observed);
        }
        ExprNode::Assign {
            target: LValue::Attr { recv, .. },
            value,
        } if matches!(&*recv.node, ExprNode::SelfRef) => {
            walk_collect_ivar_reads(value, written, order, observed);
        }
        ExprNode::Seq { exprs } => exprs
            .iter()
            .for_each(|e| walk_collect_ivar_reads(e, written, order, observed)),
        ExprNode::If {
            cond,
            then_branch,
            else_branch,
        } => {
            walk_collect_ivar_reads(cond, written, order, observed);
            walk_collect_ivar_reads(then_branch, written, order, observed);
            walk_collect_ivar_reads(else_branch, written, order, observed);
        }
        ExprNode::Send {
            recv, args, block, ..
        } => {
            if let Some(r) = recv {
                walk_collect_ivar_reads(r, written, order, observed);
            }
            args.iter()
                .for_each(|a| walk_collect_ivar_reads(a, written, order, observed));
            if let Some(b) = block {
                walk_collect_ivar_reads(b, written, order, observed);
            }
        }
        ExprNode::While { cond, body, .. } => {
            walk_collect_ivar_reads(cond, written, order, observed);
            walk_collect_ivar_reads(body, written, order, observed);
        }
        ExprNode::Return { value } => walk_collect_ivar_reads(value, written, order, observed),
        _ => {}
    }
}

/// Top-level constant declaration. Crystal: `NAME = VALUE`. TS:
/// `const NAME = VALUE;`. Rust picks a declaration shape per value
/// kind — `pub const NAME: T = V;` for scalars, `static NAME:
/// LazyLock<HashMap<K, V>> = LazyLock::new(|| HashMap::from([...]))`
/// for Hash literals, `static NAME: LazyLock<Regex> = LazyLock::new(|| ...)`
/// for regex literals. Fully-qualified paths (`std::sync::LazyLock`,
/// `regex::Regex`) avoid per-file imports — the rust emit table
/// doesn't pre-declare them and constants are emitted before classes.
pub fn format_constant(name: &str, value: &Expr) -> String {
    match &*value.node {
        ExprNode::Lit {
            value: Literal::Int { value: v },
        } => {
            format!("pub const {name}: i64 = {v}_i64;")
        }
        ExprNode::Lit {
            value: Literal::Float { value: v },
        } => {
            let s = v.to_string();
            let lit = if s.contains('.') { s } else { format!("{s}.0") };
            format!("pub const {name}: f64 = {lit};")
        }
        ExprNode::Lit {
            value: Literal::Bool { value: v },
        } => {
            format!("pub const {name}: bool = {v};")
        }
        ExprNode::Lit {
            value: Literal::Str { value: v },
        } => {
            format!("pub const {name}: &str = {v:?};")
        }
        ExprNode::Lit {
            value: Literal::Sym { value: v },
        } => {
            format!("pub const {name}: &str = {:?};", v.as_str())
        }
        ExprNode::Lit {
            value: Literal::Regex { pattern, .. },
        } => {
            // Use a raw string for the pattern so backslashes don't
            // need re-escaping. Ruby's regex syntax differs from
            // Rust's regex crate in some edge cases (lookbehind,
            // named captures); the framework Ruby's regex usage is
            // limited to character classes today, which both crates
            // share.
            format!(
                "static {name}: std::sync::LazyLock<regex::Regex> = \
                 std::sync::LazyLock::new(|| regex::Regex::new({pattern:?}).unwrap());"
            )
        }
        ExprNode::Hash { entries, .. } => format_hash_constant(name, entries),
        ExprNode::Array { elements, .. } => format_array_constant(name, elements),
        _ => format!("// TODO rust2 const: {name} = {:?}", value.node),
    }
}

fn format_hash_constant(name: &str, entries: &[(Expr, Expr)]) -> String {
    // Infer key/value types from the first entry. The body-typer's
    // Hash literal inference unifies across entries, so all keys and
    // all values share a type — sampling [0] is enough.
    let (key_ty, val_ty) = match entries.first() {
        Some((k, v)) => (rust_ty_for_constant_key(k), rust_ty_for_constant(v)),
        None => ("&'static str".to_string(), "&'static str".to_string()),
    };
    let mut pairs: Vec<String> = Vec::new();
    for (k, v) in entries {
        let k_s = render_constant_key(k);
        let v_s = render_constant_value(v);
        pairs.push(format!("({k_s}, {v_s})"));
    }
    let pairs_s = pairs.join(", ");
    format!(
        "static {name}: std::sync::LazyLock<std::collections::HashMap<{key_ty}, {val_ty}>> = \
         std::sync::LazyLock::new(|| std::collections::HashMap::from([{pairs_s}]));"
    )
}

fn format_array_constant(name: &str, elements: &[Expr]) -> String {
    let elem_ty = match elements.first() {
        Some(e) => rust_ty_for_constant(e),
        None => "&'static str".to_string(),
    };
    let items: Vec<String> = elements.iter().map(render_constant_value).collect();
    let items_s = items.join(", ");
    format!(
        "static {name}: std::sync::LazyLock<std::sync::Mutex<Vec<{elem_ty}>>> = \
         std::sync::LazyLock::new(|| std::sync::Mutex::new(vec![{items_s}]));"
    )
}

/// Hash key type — Symbol/String keys both become `&'static str` so
/// `HashMap::get(&key)` from a runtime `&str` resolves. Other key
/// shapes fall back to the value-type rule (untested but mechanical).
fn rust_ty_for_constant_key(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit {
            value: Literal::Sym { .. },
        }
        | ExprNode::Lit {
            value: Literal::Str { .. },
        } => "&'static str".to_string(),
        _ => rust_ty_for_constant(e),
    }
}

fn rust_ty_for_constant(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit {
            value: Literal::Int { .. },
        } => "i64".to_string(),
        ExprNode::Lit {
            value: Literal::Float { .. },
        } => "f64".to_string(),
        ExprNode::Lit {
            value: Literal::Bool { .. },
        } => "bool".to_string(),
        ExprNode::Lit {
            value: Literal::Str { .. },
        }
        | ExprNode::Lit {
            value: Literal::Sym { .. },
        } => "&'static str".to_string(),
        _ => "&'static str".to_string(),
    }
}

/// Render a constant key (Hash) as a Rust expression. Symbol keys
/// become string literals (matching Ruby's source-level
/// `Symbol#to_s`); string keys quote with `{:?}`-style escaping.
fn render_constant_key(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit {
            value: Literal::Sym { value },
        } => format!("{:?}", value.as_str()),
        ExprNode::Lit {
            value: Literal::Str { value },
        } => format!("{value:?}"),
        _ => render_constant_value(e),
    }
}

fn render_constant_value(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit {
            value: Literal::Int { value },
        } => format!("{value}_i64"),
        ExprNode::Lit {
            value: Literal::Float { value },
        } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        ExprNode::Lit {
            value: Literal::Bool { value },
        } => value.to_string(),
        ExprNode::Lit {
            value: Literal::Str { value },
        } => format!("{value:?}"),
        ExprNode::Lit {
            value: Literal::Sym { value },
        } => format!("{:?}", value.as_str()),
        _ => format!("/* TODO rust2 const value: {:?} */", e.node),
    }
}

#[cfg(test)]
mod op_assign_tests {
    use super::emit_library_class;

    fn emit(ruby: &str, rbs: &str) -> String {
        let classes =
            crate::runtime_src::parse_library_with_rbs(ruby.as_bytes(), rbs, "op_assign.rb")
                .expect("snippet parses and types");
        crate::emit::rust::expr::with_emit_ctx(crate::emit::rust::EmitCtx::default(), || {
            classes
                .iter()
                .map(|c| emit_library_class(c).expect("emits"))
                .collect()
        })
    }

    #[test]
    fn user_agent_comment_initializer_preserves_its_declared_array_type() {
        let ruby = std::fs::read_to_string("runtime/ruby/user_agent.rb").expect("Ruby source");
        let rbs = std::fs::read_to_string("runtime/ruby/user_agent.rbs").expect("RBS source");
        let classes = crate::runtime_src::parse_library_with_rbs(
            ruby.as_bytes(),
            &rbs,
            "user_agent.rb",
        )
        .expect("UserAgent runtime parses and types");
        let token = classes
            .iter()
            .find(|class| class.name.0.as_str() == "UserAgentToken")
            .expect("UserAgentToken class");
        let emitted = crate::emit::rust::expr::with_emit_ctx(
            crate::emit::rust::EmitCtx::default(),
            || emit_library_class(token).expect("UserAgentToken emits"),
        );

        assert!(
            emitted.contains("pub comment: Vec<String>"),
            "RBS declares the comment as Array[String], so its field must match:\n{emitted}"
        );
        assert!(
            !emitted.contains("pub comment: Vec<serde_json::Value>"),
            "the empty nil branch must not widen the declared element type:\n{emitted}"
        );

        let user_agent = classes
            .iter()
            .find(|class| class.name.0.as_str() == "UserAgent")
            .expect("UserAgent class");
        let emitted = crate::emit::rust::expr::with_emit_ctx(
            crate::emit::rust::EmitCtx::default(),
            || emit_library_class(user_agent).expect("UserAgent emits"),
        );
        assert!(
            emitted.contains("s = format!(\"{}\", DEFAULT_USER_AGENT)"),
            "assigning the static default to an owned String must emit an owned value:\n{emitted}"
        );
    }

    /// `+=` used to fall through the expression catch-all, which dropped
    /// the statement: a `while i < n; …; i += 1; end` counter never
    /// advanced, and the transpiled loop spun forever.
    #[test]
    fn op_assign_emits_the_assignment() {
        let out = emit(
            "module OpAssign\n  def self.count(n)\n    i = 0\n    s = \"\"\n    while i < n\n      s += \"x\"\n      i += 1\n    end\n    s\n  end\nend\n",
            "module OpAssign\n  def self.count: (Integer n) -> String\nend\n",
        );
        assert!(!out.contains("TODO rust2"), "OpAssign fell through:\n{out}");
        assert!(
            out.contains("i = i + 1_i64"),
            "int counter not advanced:\n{out}"
        );
        // A `+=` is a reassignment, so its local needs `let mut` as the
        // spelled-out `s = s + "x"` gets.
        assert!(
            out.contains("let mut s"),
            "`+=` local not declared mut:\n{out}"
        );
    }

    #[test]
    fn ivar_op_assign_contributes_a_struct_field() {
        let out = emit(
            "class IvarOpAssign\n  def cached\n    @cached ||= \"fallback\"\n  end\nend\n",
            "class IvarOpAssign\n  def cached: () -> String\nend\n",
        );

        assert!(
            out.contains("pub cached: Option<String>,"),
            "ivar written only through ||= was omitted:\n{out}"
        );
    }

    #[test]
    fn ivar_or_assign_uses_an_option_backing_field_and_infers_its_value_type() {
        let mut classes = crate::runtime_src::parse_library_with_rbs(
            b"class CachedValue\n  def value\n    @value ||= \"fallback\"\n  end\nend\n",
            "class CachedValue\n  def value: () -> String\nend\n",
            "ivar_or_assign.rb",
        )
        .expect("snippet parses and types");
        crate::analyze::mutates_self::propagate(&mut classes);
        let out = crate::emit::rust::expr::with_emit_ctx(crate::emit::rust::EmitCtx::default(), || {
            classes
                .iter()
                .map(|class| emit_library_class(class).expect("emits"))
                .collect::<String>()
        });

        assert!(out.contains("pub value: Option<String>,"), "{out}");
        assert!(out.contains("pub fn value(&mut self) -> String"), "{out}");
        assert!(out.contains("if self.value.is_none()"), "{out}");
        assert!(out.contains("self.value = Some(\"fallback\".to_string())"), "{out}");
        assert!(
            out.contains("self.value.as_ref().expect(\"||= initialized ivar\").clone()"),
            "{out}"
        );
    }
}

#[cfg(test)]
mod value_union_emit_tests {
    use super::emit_library_class;

    fn emit(ruby: &str, rbs: &str) -> String {
        let classes =
            crate::runtime_src::parse_library_with_rbs(ruby.as_bytes(), rbs, "value_union.rb")
                .expect("snippet parses and types");
        crate::emit::rust::expr::with_emit_ctx(crate::emit::rust::EmitCtx::default(), || {
            classes
                .iter()
                .map(|c| emit_library_class(c).expect("emits"))
                .collect()
        })
    }

    /// Heterogeneous RBS unions rust-emit as `serde_json::Value`. Display
    /// JSON-quotes strings; interpolation must use `ruby_to_s`.
    #[test]
    fn value_shaped_interpolation_uses_ruby_to_s() {
        let out = emit(
            r#"module ValueUnion
  def self.wrap(value)
    "[#{value}]"
  end
end
"#,
            r#"module ValueUnion
  def self.wrap: (String | Integer | Float | bool | nil value) -> String
end
"#,
        );
        assert!(
            out.contains("ruby_to_s"),
            "Value-shaped interp must not use Display JSON quotes:\n{out}"
        );
    }

    /// Hash#fetch(k, nil) peepholes to `Option<Value>`. A stringish param
    /// must materialize Null-on-miss before `.as_str()`.
    #[test]
    fn fetch_nil_at_string_param_materializes_owned_value() {
        let out = emit(
            r#"module ValueUnion
  def self.take_str(s)
    s
  end
  def self.escape_fetch(opts)
    take_str(opts.fetch(:title, nil))
  end
end
"#,
            r#"module ValueUnion
  def self.take_str: (String s) -> String
  def self.escape_fetch: (Hash[Symbol, untyped] opts) -> String
end
"#,
        );
        assert!(
            out.contains("unwrap_or(serde_json::Value::Null)") && out.contains("as_str()"),
            "fetch-nil at a String param must not call as_str on Option:\n{out}"
        );
    }

    fn emit_view_helpers() -> String {
        let ruby = include_str!("../../../runtime/ruby/action_view/view_helpers.rb");
        let rbs = include_str!("../../../runtime/ruby/action_view/view_helpers.rbs");
        let classes = crate::runtime_src::parse_library_with_rbs(
            ruby.as_bytes(),
            rbs,
            "action_view/view_helpers.rb",
        )
        .expect("view_helpers parses and types");
        crate::emit::rust::expr::with_emit_ctx(crate::emit::rust::EmitCtx::default(), || {
            classes
                .iter()
                .map(|c| emit_library_class(c).expect("emits"))
                .collect()
        })
    }

    fn emit_action_controller() -> String {
        let ruby = include_str!("../../../runtime/ruby/action_controller/base.rb");
        let rbs = include_str!("../../../runtime/ruby/action_controller/base.rbs");
        let classes = crate::runtime_src::parse_library_with_rbs(
            ruby.as_bytes(),
            rbs,
            "action_controller/base.rb",
        )
        .expect("action_controller/base parses and types");
        crate::emit::rust::expr::with_emit_ctx(crate::emit::rust::EmitCtx::default(), || {
            classes
                .iter()
                .map(|c| emit_library_class(c).expect("emits"))
                .collect()
        })
    }

    fn method_body<'a>(src: &'a str, name: &str) -> &'a str {
        let public = format!("pub fn {name}(");
        let crate_private = format!("pub(crate) fn {name}(");
        let (start, needle) = [public.as_str(), crate_private.as_str()]
            .into_iter()
            .filter_map(|needle| src.find(needle).map(|start| (start, needle)))
            .min_by_key(|(start, _)| *start)
            .unwrap_or_else(|| panic!("missing {name}:\n{src}"));
        let rest = &src[start..];
        let body = &rest[needle.len()..];
        let next = [
            body.find("\n    pub fn "),
            body.find("\n    pub(crate) fn "),
        ]
        .into_iter()
        .flatten()
        .min()
        .map(|i| needle.len() + i)
        .unwrap_or(rest.len());
        &rest[..next]
    }

    /// `form_with` must stringify the Hash fetch before
    /// `method_override_input(&str)`.
    #[test]
    fn form_with_stringifies_method_before_override_input() {
        let src = emit_view_helpers();
        let body = method_body(&src, "form_with");
        assert!(
            body.contains("method_override_input") && body.contains("ruby_to_s"),
            "form_with must stringify the Hash fetch:\n{body}"
        );
        assert!(
            !body.contains("method_override_input(opts"),
            "gradual opts must not cross method_override_input:\n{body}"
        );
    }

    /// Session `#[]` rust-emits `Option<String>`. `verified_request?`
    /// must use `.is_none()` / `unwrap_or_default`, not Value `.is_null()`.
    #[test]
    fn verified_request_session_nil_uses_is_none() {
        let src = emit_action_controller();
        let secret = method_body(&src, "csrf_session_secret");
        assert!(
            secret.contains("is_none()"),
            "session[] nil? should be Option::is_none:\n{secret}"
        );
        assert!(
            !secret.contains("is_null()"),
            "session[] nil? must not emit Value::is_null:\n{secret}"
        );
        assert!(
            secret.contains("unwrap_or_default()"),
            "session[] to_s should be Option unwrap_or_default:\n{secret}"
        );
        let pred = method_body(&src, "verified_request_pred");
        assert!(
            pred.contains("csrf_token_valid_pred")
                && (pred.contains("&(")
                    || pred.contains("&self.csrf_session_secret")
                    || pred.contains("&csrf_session_secret")),
            "csrf_token_valid? String args must borrow as &str:\n{pred}"
        );
        assert!(
            !pred.contains("csrf_token_valid_pred") || !pred.contains("expected.clone()"),
            "owned expected.clone() is E0308 against &str:\n{pred}"
        );
    }

    /// Column-union params render as `serde_json::Value`; `nil?` is
    /// `.is_null()`, not Option `.is_none()`.
    #[test]
    fn optional_value_attr_nil_check_uses_is_null() {
        let src = emit_view_helpers();
        let body = method_body(&src, "optional_value_attr");
        assert!(
            body.contains("is_null()"),
            "optional_value_attr nil? should be Value::is_null:\n{body}"
        );
        assert!(
            !body.contains("is_none()"),
            "optional_value_attr must not emit Option::is_none on Value:\n{body}"
        );
    }

    /// `to_s` on the column union must use fully-qualified UFCS.
    /// Method-style `.ruby_to_s()` needs `use RubyToS` in the file;
    /// ActionController does not import that trait, and a blanket
    /// `.ruby_to_s()` on every Value-rendering type broke compare rust.
    #[test]
    fn optional_value_attr_to_s_uses_ufcs() {
        let out = emit_view_helpers();
        let body = method_body(&out, "optional_value_attr");
        assert!(
            body.contains("<serde_json::Value as crate::http::RubyToS>::ruby_to_s"),
            "optional_value_attr to_s should be UFCS ruby_to_s:\n{body}"
        );
        assert!(
            !body.contains(".ruby_to_s()"),
            "method-style ruby_to_s needs the trait in scope:\n{body}"
        );
    }

    /// `turbo_stream_from`'s `String | Array[untyped]` renders as Value
    /// on rust only. Wrap scalar call-site args here, not in the shared
    /// lowerer — that Cast wrapping broke ActionController on extras.
    #[test]
    fn union_param_string_arg_wraps_as_value() {
        let ruby = r#"module VH
  def self.turbo_stream_from(stream, channel)
    stream.to_s + channel
  end
  def self.call
    turbo_stream_from("articles", "Turbo::StreamsChannel")
  end
end
"#;
        let rbs = r#"module VH
  def self.turbo_stream_from: (String | Array[untyped] stream, String channel) -> String
  def self.call: () -> String
end
"#;
        let classes = crate::runtime_src::parse_library_with_rbs(ruby.as_bytes(), rbs, "vh.rb")
            .expect("snippet parses and types");
        let out =
            crate::emit::rust::expr::with_emit_ctx(crate::emit::rust::EmitCtx::default(), || {
                classes
                    .iter()
                    .map(|c| emit_library_class(c).expect("emits"))
                    .collect::<String>()
            });
        let body = method_body(&out, "call");
        assert!(
            body.contains("serde_json::Value::from") && body.contains("articles"),
            "string arg to String|Array union must wrap Value::from:\n{body}"
        );
    }

    /// Runtime emit uses an empty EmitCtx, so ActionController Const
    /// helpers must coerce from `external_class_method_param_tys`.
    /// HeaderStore `[]=` takes `Option<String>`, not Value.
    #[test]
    fn action_controller_runtime_emit_typechecks_hotspots() {
        let src = emit_action_controller();
        let set_index = method_body(&src, "set_index");
        assert!(
            set_index.contains("header_key_ok_pred(Some("),
            "header_key_ok? takes String?, wrap &str:\n{set_index}"
        );
        let key_at = method_body(&src, "key_at");
        assert!(
            !key_at.contains(".map("),
            "keys[i].to_s on Array[String] must not Option-map a plain String:\n{key_at}"
        );
        let val_at = method_body(&src, "val_at");
        assert!(
            val_at.contains(".map(|v| v.to_string()).unwrap_or_default()"),
            "nil in HeaderStore's String? values must stringify to the empty String:\n{val_at}"
        );
        let render = method_body(&src, "render");
        assert!(
            render.contains("sanitize_location(&("),
            "sanitize_location takes &str, borrow the unwrapped String:\n{render}"
        );
        let send_data = method_body(&src, "send_data");
        assert!(
            send_data.contains("set_index(") && send_data.contains("Some("),
            "HeaderStore []= must wrap Option<String>, not Value::from:\n{send_data}"
        );
        assert!(
            !send_data.contains("Value::from"),
            "HeaderStore []= must not coerce through Value:\n{send_data}"
        );
        let csrf = method_body(&src, "__rh_static_request_for_csrf");
        assert!(
            csrf.contains("None;"),
            "nil-only void method emits its nil expression as a statement:\n{csrf}"
        );
    }
}

#[cfg(test)]
mod implicit_self_dispatch_tests {
    use super::emit_library_class;

    fn emit(source: &[u8], rbs: &str, path: &str) -> String {
        let mut classes = crate::runtime_src::parse_library_with_rbs(source, rbs, path)
            .expect("snippet parses and types");
        crate::analyze::mutates_self::propagate(&mut classes);
        crate::emit::rust::expr::with_emit_ctx(crate::emit::rust::EmitCtx::default(), || {
            classes
                .iter()
                .map(|class| emit_library_class(class).expect("emits"))
                .collect::<String>()
        })
    }

    #[test]
    fn bare_instance_calls_keep_their_implicit_receiver() {
        let out = emit(
            b"class ImplicitReader\n  attr_reader :message\n  def initialize(message)\n    @message = message\n  end\n  def render\n    formatted_message\n  end\n  def formatted_message\n    message\n  end\nend\n",
            "class ImplicitReader\n  @message: String\n  def initialize: (String message) -> void\n  def message: () -> String\n  def render: () -> String\n  def formatted_message: () -> String\nend\n",
            "implicit_reader.rb",
        );

        assert!(out.contains("pub fn render(&self) -> String"), "{out}");
        assert!(out.contains("self.formatted_message()"), "{out}");
        assert!(out.contains("self.message()"), "{out}");
    }

    #[test]
    fn static_safe_methods_keep_instance_wrappers_and_sibling_dispatch() {
        let out = emit(
            b"class StaticChain\n  def normalize(value)\n    value.strip\n  end\n  def normalize_with_prefix(value)\n    normalize(value)\n  end\n  def initialize(value)\n    @value = normalize(value)\n  end\n  def formatted\n    normalize_with_prefix(@value)\n  end\nend\n",
            "class StaticChain\n  @value: String\n  def normalize: (String value) -> String\n  def normalize_with_prefix: (String value) -> String\n  def initialize: (String value) -> void\n  def formatted: () -> String\nend\n",
            "static_chain.rb",
        );

        assert!(
            out.contains("pub(crate) fn __rh_static_normalize(value: &str)"),
            "{out}"
        );
        assert!(
            out.contains("pub fn normalize(&self, value: &str)"),
            "{out}"
        );
        assert!(out.contains("Self::__rh_static_normalize"), "{out}");
        assert!(
            out.contains("pub fn normalize_with_prefix(&self, value: &str)"),
            "{out}"
        );
        assert!(out.contains("self.normalize(&("), "{out}");
        assert!(out.contains("pub fn formatted(&self) -> String"), "{out}");
        assert!(out.contains("self.normalize_with_prefix("), "{out}");
    }

    #[test]
    fn compound_ivar_assignment_requires_an_instance_receiver() {
        let out = emit(
            b"class Counter\n  def initialize\n    @count = 0\n  end\n  def increment\n    @count += 1\n  end\nend\n",
            "class Counter\n  @count: Integer\n  def initialize: () -> void\n  def increment: () -> Integer\nend\n",
            "counter.rb",
        );

        assert!(out.contains("pub fn increment(&mut self) -> i64"), "{out}");
    }

    #[test]
    fn class_method_does_not_dispatch_to_same_named_instance_method() {
        let out = emit(
            b"class ScopeCollision\n  def name\n    @name\n  end\n  def self.label\n    name\n  end\nend\n",
            "class ScopeCollision\n  @name: String\n  def name: () -> String\n  def self.label: () -> String\nend\n",
            "scope_collision.rb",
        );

        let label = out
            .split("pub fn label")
            .nth(1)
            .expect("class method emitted");
        assert!(!label.contains("self.name()"), "{out}");
    }
}

#[cfg(test)]
mod keyword_field_emit_tests {
    use super::emit_library_class;

    #[test]
    fn rust_keywords_are_escaped_consistently_for_instance_fields() {
        let classes = crate::runtime_src::parse_library_with_rbs(
            b"class KeywordField\n  def initialize\n    @type = \"text\"\n  end\n  def type\n    @type\n  end\nend\n",
            "class KeywordField\n  def initialize: () -> void\n  def type: () -> String\nend\n",
            "keyword_field.rb",
        )
        .expect("snippet parses and types");
        let out =
            crate::emit::rust::expr::with_emit_ctx(crate::emit::rust::EmitCtx::default(), || {
                classes
                    .iter()
                    .map(|class| emit_library_class(class).expect("emits"))
                    .collect::<String>()
            });

        assert!(
            out.contains("pub r#type: String"),
            "field not escaped:\n{out}"
        );
        assert!(
            out.contains("let mut r#type"),
            "constructor local not escaped:\n{out}"
        );
        assert!(
            out.contains("self.r#type"),
            "field read not escaped:\n{out}"
        );
        assert!(
            out.contains("Self { r#type }"),
            "struct literal not escaped:\n{out}"
        );
    }
}

#[cfg(test)]
mod numeric_unary_emit_tests {
    use super::emit_library_class;

    fn emit(ruby: &str, rbs: &str) -> String {
        let classes = crate::runtime_src::parse_library_with_rbs(ruby.as_bytes(), rbs, "unary.rb")
            .expect("snippet parses and types");
        let mut app = crate::App::new();
        app.library_classes = classes;
        crate::lower::numeric_unary::apply_numeric_unary_lowering(&mut app);
        crate::emit::rust::decide::decide_classes(&mut app.library_classes);
        crate::emit::rust::expr::with_emit_ctx(crate::emit::rust::EmitCtx::default(), || {
            app.library_classes.iter().map(|c| emit_library_class(c).expect("emits")).collect()
        })
    }

    /// `-n` is a `-@` send; it used to come out as the method call
    /// `n.-@()`, which does not parse. `(-5).abs` lost its parens, and
    /// `-5_i64.abs()` is `-(5_i64.abs())`: -5, with no error anywhere.
    #[test]
    fn negation_is_arithmetic_and_negative_receivers_keep_parens() {
        let out = emit(
            "module Unary\n  def self.neg(n)\n    -n\n  end\n  def self.neg_sum(n)\n    -(n + 4)\n  end\n  def self.pos(n)\n    +n\n  end\n  def self.neg_abs\n    (-5).abs\n  end\n  def self.diff_abs(n)\n    (n - 10).abs\n  end\nend\n",
            "module Unary\n  def self.neg: (Integer n) -> Integer\n  def self.neg_sum: (Integer n) -> Integer\n  def self.pos: (Integer n) -> Integer\n  def self.neg_abs: () -> Integer\n  def self.diff_abs: (Integer n) -> Integer\nend\n",
        );
        assert!(!out.contains("-@") && !out.contains("+@"), "operator method leaked:\n{out}");
        assert!(out.contains("n * -1_i64"), "`-n` not lowered:\n{out}");
        assert!(out.contains("(n + 4_i64) * -1_i64"), "`-(n + 4)` re-associated:\n{out}");
        assert!(out.contains("(-5_i64).abs()"), "negative receiver lost its parens:\n{out}");
        assert!(out.contains("(n - 10_i64).abs()"), "infix receiver lost its parens:\n{out}");
    }
}
