//! A call to a method a state-machine declaration generates names the
//! declaration and its gem (#142). Attribution only: the method stays
//! unresolved and the emitted program still has no `publish!`.

use std::collections::HashMap;
use std::path::PathBuf;

use roundhouse::analyze::attribution::{
    attribute_generated_names, attribute_ingest_gaps, attribute_unknown_gems,
};
use roundhouse::analyze::{Analyzer, diagnose};
use roundhouse::diagnostic::{Diagnostic, DiagnosticKind, Severity};
use roundhouse::ingest::{IngestError, ingest_app_from_tree, survey};

const LOCK: &str = "GEM
  remote: https://rubygems.org/
  specs:
    aasm (6.0.0)
    paper_trail (16.0.0)
    rails (8.1.4)
    state_machines-activerecord (0.200.0)

DEPENDENCIES
  aasm
  paper_trail
  rails
  state_machines-activerecord
";

const ARTICLE: &str = "class Article < ApplicationRecord
  include Moderation

  aasm column: :state do
    state :draft, initial: true
    state :published

    event :publish do
      transitions from: :draft, to: :published
    end
  end

  def headline
    title
  end
end
";

const MODERATION: &str = "module Moderation
  extend ActiveSupport::Concern

  included do
    state_machine :status, initial: :open do
      event :close do
        transition open: :closed
      end
    end
  end
end
";

const SHOW: &str = "class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
    @article.publish! if @article.may_publish?
    @versions = @article.versions
    @article.close if @article.can_close?
    @drafts = Article.draft
    @typo = @article.titel
    @comment = Comment.new
    @comment.publish!
    render plain: 'ok'
  end
end
";

fn tree(lock: Option<&str>) -> HashMap<PathBuf, Vec<u8>> {
    let mut files = vec![
        ("app/models/application_record.rb", "class ApplicationRecord < ActiveRecord::Base\nend\n"),
        ("app/models/article.rb", ARTICLE),
        ("app/models/comment.rb", "class Comment < ApplicationRecord\nend\n"),
        ("app/models/concerns/moderation.rb", MODERATION),
        ("app/controllers/application_controller.rb", "class ApplicationController < ActionController::Base\nend\n"),
        ("app/controllers/articles_controller.rb", SHOW),
        ("config/routes.rb", "Rails.application.routes.draw do\n  resources :articles, only: :show\nend\n"),
        (
            "db/schema.rb",
            "ActiveRecord::Schema.define do\n  create_table :articles do |t|\n    t.string :title\n    t.string :state\n    t.string :status\n  end\n  create_table :comments do |t|\n    t.string :body\n  end\nend\n",
        ),
    ];
    files.extend(lock.map(|l| ("Gemfile.lock", l)));
    files.into_iter().map(|(p, s)| (PathBuf::from(p), s.as_bytes().to_vec())).collect()
}

/// `check`'s order: generated names, then ingest gaps, then unknown gems.
fn check(files: HashMap<PathBuf, Vec<u8>>, continue_: bool) -> (Vec<Diagnostic>, Vec<IngestError>) {
    if continue_ {
        survey::activate();
    }
    let result = ingest_app_from_tree(files);
    let gaps = if continue_ { survey::drain() } else { Vec::new() };
    let mut app = result.expect("ingest");
    Analyzer::new(&app).analyze(&mut app);
    let mut diags = diagnose(&app);
    attribute_generated_names(&mut diags, &app);
    attribute_ingest_gaps(&mut diags, &app, &gaps);
    attribute_unknown_gems(&mut diags, &app);
    (diags, gaps)
}

fn dispatch<'a>(diags: &'a [Diagnostic], method: &str, recv: &str) -> &'a Diagnostic {
    diags
        .iter()
        .find(|d| {
            matches!(&d.kind, DiagnosticKind::SendDispatchFailed { method: m, recv_ty }
                if m.as_str() == method && format!("{recv_ty:?}").contains(&format!("\"{recv}\"")))
        })
        .unwrap_or_else(|| panic!("no dispatch failure for `{method}` on {recv}: {diags:#?}"))
}

fn assert_note(d: &Diagnostic, needle: &str) {
    assert_eq!(d.severity, Severity::Info, "{}", d.message);
    assert!(d.message.contains(needle), "`{needle}` missing from: {}", d.message);
}

#[test]
fn generated_names_are_notes_naming_their_declaration_and_gem() {
    for continue_ in [false, true] {
        let (diags, gaps) = check(tree(Some(LOCK)), continue_);
        let aasm = "generated by the `aasm` declaration in Article; the `aasm` gem";
        assert_note(dispatch(&diags, "publish!", "Article"), aasm);
        assert_note(dispatch(&diags, "may_publish?", "Article"), aasm);
        assert_note(dispatch(&diags, "draft", "Article"), aasm);
        // Declared in a concern's `included do`, called on the includer.
        let machine =
            "generated by the `state_machine` declaration in Moderation; the `state_machines-activerecord` gem";
        assert_note(dispatch(&diags, "close", "Article"), machine);
        assert_note(dispatch(&diags, "can_close?", "Article"), machine);
        // Only names a declaration generates, and only on its receivers.
        assert_eq!(dispatch(&diags, "publish!", "Comment").severity, Severity::Error);
        if !continue_ {
            // A fixed-surface gem is unchanged, and a typo stays an error.
            assert_note(dispatch(&diags, "versions", "Article"), "the `paper_trail` gem");
            assert_eq!(dispatch(&diags, "titel", "Article").severity, Severity::Error);
        } else {
            // Under `--continue` the survey gap in article.rb claims the
            // rest of Article first, as any gap does (deliberately
            // over-broad), ahead of the unknown-gem pass.
            for method in ["versions", "titel"] {
                assert_note(dispatch(&diags, method, "Article"), "ingest gap in app/models/article.rb");
            }
        }
        if continue_ {
            let messages: Vec<String> = gaps.iter().map(|g| g.to_string()).collect();
            assert!(
                messages.iter().any(|m| m.contains("state-machine DSL block `aasm` is not modeled")),
                "the survey names the dropped block: {messages:?}"
            );
        }
    }
}

#[test]
fn without_the_gem_in_the_lock_the_names_stay_errors() {
    let (diags, _) = check(tree(None), false);
    assert_eq!(dispatch(&diags, "publish!", "Article").severity, Severity::Error);
    assert_eq!(dispatch(&diags, "close", "Article").severity, Severity::Error);

    let aasm_only = LOCK.replace("    state_machines-activerecord (0.200.0)\n", "");
    let (diags, _) = check(tree(Some(&aasm_only)), false);
    assert_eq!(dispatch(&diags, "publish!", "Article").severity, Severity::Info);
    assert_eq!(
        dispatch(&diags, "close", "Article").severity,
        Severity::Error,
        "a declaration whose gem is absent claims nothing"
    );
}
