# Path router: matches (method, path) against a typed route table and
# resolves to (controller, action, path_params).
#
# In real-blog this is generated by Rails from `config/routes.rb`'s
# `resources` DSL; in spinel-blog it's a flat data structure (see
# `config/routes.rb`). The eventual transpiler reproduces this shape
# from the DSL declarations.
#
# Route rows are typed `Route` instances (not `Hash[Symbol, untyped]`)
# so strict-typed targets (Rust, Crystal) compile against per-field
# types instead of falling through an `untyped` value channel. Path
# captures land as `Hash[String, String]` — URL segments are always
# strings.

module ActionDispatch
  module Router
    # One entry in the route table. Promoted from
    # `Hash[Symbol, String|Symbol]` to a typed class so each per-field
    # type is statically known. `verb` rather than `method` to avoid
    # shadowing Ruby's `Object#method` reflection method.
    #
    # Positional `initialize` (not kwarg) — the per-target emitters
    # convert def-time kwargs to positional but don't unpack kwarg-style
    # call sites; positional avoids the asymmetry on internal classes
    # like this one.
    class Route
      attr_reader :verb, :pattern, :controller, :action, :req_format, :int_params,
                  :pattern_parts

      # `req_format` — the route-forced response format (Rails'
      # `get "/rss" => "home#index", :format => "rss"`), nil for the
      # common infer-from-path case. Named `req_format` (not `format`)
      # so targets whose stdlibs claim `format` never collide.
      #
      # `int_params` — space-joined names of path params constrained to
      # digit-only segments (Roda's `Integer` matcher, Rails digit-class
      # `constraints:`), e.g. `"id"` or `"article_id id"`; the empty
      # string for the unconstrained common case. Carried as a delimited
      # String rather than `Array[String]` so this optional positional
      # stays a single scalar type on strict/AOT targets — a `nil`-or-`[]`
      # optional tail collapses to `Any?`/a bare variadic on Swift,
      # Kotlin, Go, and Spinel. A candidate segment that isn't all digits
      # makes the route a non-match, so `/articles/12abc` falls through
      # to 404 instead of binding `id = "12abc"`.
      def initialize(verb, pattern, controller, action, req_format = nil, int_params = +"")
        @verb        = verb
        @pattern     = pattern
        @controller  = controller
        @action      = action
        @req_format  = req_format
        @int_params  = int_params
        # Split ONCE, at table-construction time. `Router.match` is a linear
        # scan, so splitting the pattern inside the match loop charged every
        # request two fresh segment arrays per candidate route it walked past
        # — profiled at 43% of a lobsters `/about` request (112 candidates
        # deep in the table) and ~2.7 array allocations per candidate. The
        # table is built once at boot; the request path is the only thing
        # that has to be split per request.
        @pattern_parts = pattern.split("/")
      end
    end

    # The result of a successful `Router.match` call: the resolved
    # controller symbol, action symbol, and captured path parameters.
    # Replaces the prior `{ controller:, action:, path_params: }` hash
    # return shape. Positional initialize, same rationale as Route.
    class MatchResult
      attr_reader :controller, :action, :path_params, :req_format

      def initialize(controller, action, path_params, req_format = nil)
        @controller  = controller
        @action      = action
        @path_params = path_params
        @req_format  = req_format
      end
    end

    # Match a request against the route table. Returns a `MatchResult`
    # on success; nil otherwise.
    def self.match(method, path, table)
      # Rails' `(.:format)`: every route's last segment may carry a
      # `.ext` that names the RESPONSE FORMAT and is not part of the
      # path. `POST /rooms/3/messages.turbo_stream` is the same route as
      # `POST /rooms/3/messages`, with `params["format"]` set.
      #
      # THE STRIPPED FORM IS TRIED FIRST, and that order is the whole
      # point. Rails compiles a dynamic segment to `[^/.?]+` — a dot can
      # NEVER land inside one — so `(.:format)` is peeled off before any
      # segment is bound. Trying the literal path first instead let a
      # `:id` segment SWALLOW the extension: `DELETE /rooms/3/messages/
      # 6.turbo_stream` matched `/rooms/:room_id/messages/:id` with
      # `id = "6.turbo_stream"`, and since `find` coerces that back to 6
      # the action ran and only the FORMAT was lost — the turbo_stream
      # template was never reached and the request died in
      # MissingTemplate. The asymmetry hid it: a COLLECTION path
      # (`/rooms/3/messages.turbo_stream`) has a literal last segment
      # that cannot swallow anything, so those routes worked and only
      # member routes were wrong.
      #
      # The literal path stays as the FALLBACK, which is what keeps a
      # route whose path genuinely contains a dot working: `/manifest
      # .json` strips to `/manifest`, matches no route, and falls
      # through to itself. `/robots.txt` never strips at all — `txt` is
      # not a registered format. A dotted segment whose extension is not
      # a format (`/domains/example.com`) is likewise untouched, which
      # is exactly Rails' rule for the same URL.
      #
      # Divergence, small and named: an app declaring BOTH `/manifest`
      # and `/manifest.json` gets the former for `/manifest.json`, where
      # Rails picks by declaration order. No corpus app declares such a
      # pair.
      #
      # Split on "." rather than `rindex`-and-slice: that is a Ruby
      # string idiom several targets' emitters do not carry, and the
      # whole point of this file is that it compiles everywhere. One
      # split of the WHOLE path, not a split of its last segment: the
      # extension must be in the last segment, and `include?("/")` says
      # so directly — while splitting twice asks an emitter to
      # materialize a `split` off a local rather than a parameter.
      dotted = path.split(".")
      if dotted.length >= 2
        ext = dotted[dotted.length - 1]
        if !ext.include?("/") && format_extension(ext)
          # Trimming from the FULL path (rather than rewriting the
          # segment array and re-joining) avoids an array index
          # ASSIGNMENT, which is another shape not every emitter carries.
          stripped = match_path(method, path[0, path.length - ext.length - 1].to_s, table, ext)
          return stripped unless stripped.nil?
        end
      end
      match_path(method, path, table, +"")
    end

    # Is `ext` one of Rails' registered format extensions? The registry
    # PORTED WHOLE rather than grown one entry at a time as apps hit it:
    # the dispatchers sniffed a hardcoded `.json` and nothing else, so
    # `POST /rooms/3/messages.turbo_stream` matched no route at all. It
    # is a closed set with a published membership, which is exactly the
    # kind of table to copy rather than derive.
    #
    # A space-delimited STRING scanned by split-and-compare — literally
    # the shape `int_constrained` below uses for the digit-constraint
    # list, and chosen for the same reason: it is the one membership
    # test every target emits correctly. A module-level constant Hash is
    # where the emitters diverge most (Elixir binds a module attribute
    # to the file's FIRST `defmodule`, which here is `Route`, not
    # `Router`; the strict targets each type a constant hash's values
    # differently), and even substring matching needs a concatenation
    # rust rejects at `str::contains`.
    #
    # No `?` suffix, for the reason `int_constrained` states below: the
    # Elixir lowering appends `__loop` to a while-loop method's own
    # name, and `?` can only END an Elixir identifier. That comment is
    # the only thing standing between this file and the same failure
    # twice — which is what it is for.
    def self.format_extension(ext)
      known = "html text js css ics csv vcf vtt png jpeg jpg gif bmp tiff svg webp mpeg mp3 mp4 ogg webm otf ttf woff woff2 pdf zip gzip xml rss atom yaml json turbo_stream".split(" ")
      i = 0
      while i < known.length
        return true if known[i] == ext
        i += 1
      end
      false
    end

    # One scan of the table for a literal path. `format` is the
    # extension the REQUEST carried ("" when it carried none); it
    # reaches the action as `params["format"]`, which is where Rails
    # puts the `(.:format)` segment.
    #
    # A HEAD request is Rails' two-pass rule (Journey's
    # `match_head_routes`): a route declared for HEAD itself wins;
    # failing that, the request is routed as the GET it shadows. Without
    # the second pass `HEAD /` — what an uptime monitor or a deploy
    # proxy sends — 404'd on every app, since no `rails new` app
    # declares a HEAD route. The verb the ACTION sees stays HEAD;
    # dropping the body is the server's job, as it is Rack's.
    def self.match_path(method, path, table, format)
      method_upcase = method.to_s.upcase
      path_parts = path.split("/")
      hit = scan_routes(method_upcase, path_parts, table, format)
      if hit.nil? && method_upcase == "HEAD"
        return scan_routes("GET", path_parts, table, format)
      end
      hit
    end

    # One pass of the table for one verb, over the already-split path.
    def self.scan_routes(method_upcase, path_parts, table, format)
      i = 0
      while i < table.length
        route = table[i]
        # "ANY" is `match …, via: :all`: Rails routes it for every verb.
        # Not on the HEAD pass, though: Rails' first HEAD pass takes only
        # routes that name a verb, so a `via: :all` route is reached on
        # the GET pass, in declaration order with the GET routes.
        verb = route.verb.to_s
        if verb == method_upcase || (verb == "ANY" && method_upcase != "HEAD")
          params = match_parts(route.pattern_parts, path_parts, route.int_params, format)
          unless params.nil?
            return ActionDispatch::Router::MatchResult.new(route.controller, route.action, params, route.req_format)
          end
        end
        i += 1
      end
      nil
    end

    # Match a path against a pattern containing `:name` segments.
    # Returns a `Hash[String, String]` of captured params, or nil
    # if no match. No regex; segment-by-segment compare. Captures
    # are always string-to-string — URL segments are strings, and
    # the typed-hash form survives strict-typed targets (Crystal,
    # Rust). Callers index by string key (`params["id"]`).
    #
    # `int_params` (optional) is the route's space-joined digit-only
    # constraint list. A constrained `:name` segment whose value isn't
    # all digits makes the whole pattern a non-match — `Router.match`
    # keeps scanning and the request 404s. The check runs here on the
    # raw segment (`ap`, a non-nil String local) rather than after
    # capture so no target has to model `Hash#[]` returning nil.
    def self.match_pattern(pattern, path, int_params = +"")
      match_parts(pattern.split("/"), path.split("/"), int_params)
    end

    # The segment loop, over already-split parts. `Router.match` feeds it the
    # route's precomputed `pattern_parts` and the request path split once for
    # the whole scan, so a table walk allocates nothing per candidate.
    # `match_pattern` above keeps the split-here-from-two-strings signature —
    # it is the shape the runtime tests and the per-target smoke tests call,
    # and a tree-shake root in src/runtime_loader.rs.
    # `format` is the extension `Router.match` stripped off the path
    # ("" when there was none). It lands in the captured params, which
    # is where Rails puts the `(.:format)` segment — and it is captured
    # HERE, beside the `:name` segments, rather than inserted into the
    # returned hash by the caller: this is the only place the hash is a
    # freshly-built local of known shape, and a strict emitter types a
    # write into a returned-and-nil-checked hash differently.
    #
    # A `*name` GLOB segment — Rails' `*filename` on the Active Storage
    # engine's routes — must be LAST in the pattern and takes every
    # remaining path segment, slash-joined, as its value. A glob route
    # therefore matches any path at least as long as its pattern; every
    # other route still needs an exact segment count.
    def self.match_parts(pattern_parts, path_parts, int_params = +"", format = +"")
      # The tail segment is bound to a local before it is asked anything,
      # like `pp`/`ap` below: an array index read straight into a method
      # call is what some strict emitters coerce as nilable.
      last = pattern_parts.length - 1
      globbed = false
      if last >= 0
        tail = pattern_parts[last]
        globbed = tail.start_with?("*")
      end
      if globbed
        return nil if path_parts.length < pattern_parts.length
      elsif pattern_parts.length != path_parts.length
        return nil
      end
      # Literal segments first, allocating nothing: `/up` is the last of
      # campfire's ~180 routes, and every same-length GET route before it
      # built a params Hash (and a `:name` substring per segment) only to
      # fail on its first literal — 37% of that request's allocations.
      return nil unless literals_match(pattern_parts, path_parts)
      params = {}
      params["format"] = format unless format.empty?
      i = 0
      while i < pattern_parts.length
        pp = pattern_parts[i]
        ap = path_parts[i]
        if pp.start_with?("*")
          params[pp[1..]] = glob_rest(path_parts, i)
        elsif pp.start_with?(":")
          name = pp[1..]
          # `seg = ap.to_s` (not `digits_only(ap)` directly): some strict
          # emitters track a bare array-index local as nilable and coerce
          # it wrongly at a non-nilable call arg; routing the segment
          # through `to_s` first hands `digits_only` a definite String.
          seg = ap.to_s
          if int_constrained(int_params, name) && !digits_only(seg)
            return nil
          end
          # The route parameter is the same value checked above. Reuse the
          # local rather than reading `ap` again, which keeps ownership clear
          # in strict targets while preserving Ruby's string value semantics.
          params[name] = seg
        elsif pp != ap
          # A literal PREFIX before the `:name` in the same segment —
          # lobsters' `/~:username` and `/@:username`. Rails binds the
          # rest of the segment after the prefix. Checked only on a
          # mismatch, and behind `include?`, so a plain literal segment
          # costs what it did.
          return nil unless pp.include?(":")
          plen = param_prefix_length(pp)
          return nil if plen <= 0 || ap.length <= plen
          return nil unless ap.start_with?(pp[0, plen].to_s)
          params[pp[plen + 1, pp.length].to_s] = ap[plen, ap.length].to_s
        end
        i += 1
      end
      decode_captures(params)
    end

    # Route matching and constraints operate on the encoded path. Decode only
    # after the entire pattern matches, so an escaped slash or dot cannot
    # change segmentation and a rejected route cannot raise while decoding.
    def self.decode_captures(params)
      decoded = {}
      # Snapshot name/value pairs before decoding. Every capture is a String,
      # and the input is immutable, so the even-length pair array is stable.
      # Encoding errors stay outside the nonthrowing collection callback.
      pairs = capture_pairs(params)
      i = 0
      while i < pairs.length
        name = capture_part(pairs, i)
        value = capture_part(pairs, i + 1)
        decoded[name] = decode_capture(value)
        i += 2
      end
      decoded
    end

    # Retain Hash iteration order as adjacent String name/value pairs. This
    # callback only snapshots data and cannot raise an encoding error.
    def self.capture_pairs(params)
      pairs = []
      params.each do |name, value|
        # Force an owned string on strict targets whose Hash iterator
        # yields borrowed keys (Rust's `HashMap::iter`, for example).
        # Concatenating the empty string preserves the value while making
        # the snapshot independent of the borrowed map entry.
        pairs << (name.to_s + "")
        pairs << value
      end
      pairs
    end

    # Internal String-only pair access. The caller visits an even-length
    # snapshot two entries at a time, proving both nonnegative indexes exist.
    def self.capture_part(pairs, index)
      part = pairs[index]
      raise ArgumentError, "Missing internal route capture part" if part.nil?
      part
    end

    # Decode bytes before interpreting UTF-8: one character may mix raw and
    # percent-escaped bytes. A literal '+' is preserved, unlike form decoding.
    # String#bytes materializes once, including for Unicode-native targets.
    def self.decode_capture(value)
      bytes = percent_bytes(value.bytes)
      out = +""
      i = 0
      while i < bytes.length
        byte = capture_byte(bytes, i)
        width = utf8_width(byte)
        character = utf8_character(bytes, i, byte, width)
        out = out + character
        i += width
      end
      out
    end

    # Classify one lead byte without carrying branch-mutated state between
    # sequences. Continuation bytes and invalid leads cannot start a character.
    def self.utf8_width(byte)
      return 4 if byte >= 0xF0 && byte <= 0xF4
      return 3 if byte >= 0xE0 && byte <= 0xEF
      return 2 if byte >= 0xC2 && byte <= 0xDF
      raise ArgumentError, "Invalid encoding for path parameter" if byte >= 0x80
      1
    end

    # Validate one decoded UTF-8 sequence before constructing its scalar.
    # Bounds reject truncated, overlong, surrogate and out-of-range sequences.
    # Byte-array indices stay within the checked Integer-only sequence.
    def self.utf8_character(bytes, from, first, width)
      raise ArgumentError, "Invalid encoding for path parameter" if from + width > bytes.length
      cp = first
      if width == 2
        cp = first - 0xC0
      elsif width == 3
        cp = first - 0xE0
      elsif width == 4
        cp = first - 0xF0
      end
      j = 1
      while j < width
        byte = capture_byte(bytes, from + j)
        if byte < 0x80
          raise ArgumentError, "Invalid encoding for path parameter"
        end
        if byte > 0xBF
          raise ArgumentError, "Invalid encoding for path parameter"
        end
        cp = cp * 64 + byte - 0x80
        j += 1
      end
      if (width == 2 && cp < 0x80) || (width == 3 && cp < 0x800) ||
         (width == 4 && cp < 0x10000) || (cp >= 0xD800 && cp <= 0xDFFF) || cp > 0x10FFFF
        raise ArgumentError, "Invalid encoding for path parameter"
      end
      cp.chr(Encoding::UTF_8)
    end

    # Invalid/incomplete escapes stay literal, as in Rails' path decoder.
    # Advance over the original input only: %25FF becomes literal %FF.
    def self.percent_bytes(bytes)
      decoded = []
      i = 0
      while i < bytes.length
        byte = percent_byte(bytes, i)
        advance = percent_advance(byte)
        if byte < 0
          decoded << capture_byte(bytes, i)
        else
          decoded << byte
        end
        # One trailing counter step also permits functional targets to lower
        # the scan into recursion without changing single-decoding semantics.
        i += advance
      end
      decoded
    end

    # The escape parser's negative sentinel consumes one literal byte;
    # a decoded escape consumes its three original bytes exactly once.
    def self.percent_advance(byte)
      return 1 if byte < 0
      3
    end

    # A valid %HH escape at this byte offset, or -1 to retain literal bytes.
    def self.percent_byte(bytes, at)
      return -1 if at + 2 >= bytes.length
      return -1 if capture_byte(bytes, at) != 37
      hi = hex_digit(capture_byte(bytes, at + 1))
      lo = hex_digit(capture_byte(bytes, at + 2))
      return -1 if hi < 0
      return -1 if lo < 0
      hi * 16 + lo
    end

    # Check the offset before indexing an Integer-only byte array. The method
    # contract carries the guaranteed Integer result to callers on every target.
    def self.capture_byte(bytes, index)
      raise ArgumentError, "Invalid encoding for path parameter" if index < 0
      raise ArgumentError, "Invalid encoding for path parameter" if index >= bytes.length
      byte = bytes[index]
      raise ArgumentError, "Invalid encoding for path parameter" if byte.nil?
      byte
    end

    # ASCII hexadecimal classification without Unicode case folding.
    def self.hex_digit(byte)
      return byte - 48 if byte >= 48 && byte <= 57
      return byte - 65 + 10 if byte >= 65 && byte <= 70
      return byte - 97 + 10 if byte >= 97 && byte <= 102
      -1
    end

    # A decoded capture path-escaped again, for a routing redirect's
    # `%{name}`: Rails fills it with `Journey::Router::Utils.escape_path`
    # of the decoded value, so a `#` or `?` in it stays part of the path.
    # Walks bytes (not characters): after `decode_capture`, a multibyte
    # scalar is real UTF-8 in the string, and each byte of it must become
    # `%XX` the way Rails re-encodes `/articles/josé` as `/articles/jos%C3%A9`.
    # PATH-safe printable ASCII (unreserved, sub-delims, `:`, `@`, `/`)
    # passes; every other byte is `%` + two hex digits.
    def self.escape_path(s)
      out = ""
      bytes = s.bytes
      i = 0
      while i < bytes.length
        b = capture_byte(bytes, i)
        if path_byte_ok(b)
          out = out + printable[b - 32, 1].to_s
        else
          out = out + percent_escape_byte(b)
        end
        i += 1
      end
      out
    end

    # Printable ASCII, 0x20 to 0x7E in order: the character for byte
    # `code` is `printable[code - 32, 1]`.
    def self.printable
      " !\"\#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"
    end

    # Whether byte `b` may appear unescaped in a PATH (Rails' escape_path set).
    def self.path_byte_ok(b)
      return false if b < 32 || b > 126
      c = printable[b - 32, 1].to_s
      return false if c == " "
      return false if c == "\""
      return false if c == "#"
      return false if c == "%"
      return false if c == "<"
      return false if c == ">"
      return false if c == "?"
      return false if c == "["
      return false if c == "\\"
      return false if c == "]"
      return false if c == "^"
      return false if c == "`"
      return false if c == "{"
      return false if c == "|"
      return false if c == "}"
      true
    end

    # One byte as `%` + two uppercase hex digits (Rails' PATH escape).
    # Quotient and remainder by repeated subtract — not `/`. Python and
    # Elixir emit Int/Int `/` as true division, so `b / 16` became
    # `2.1875` for `#` and broke every `%{name}` escape that needed a
    # non-PATH byte (MEASURED on the #456 tip emit). One `while` so the
    # Elixir lowering stays in shape.
    def self.percent_escape_byte(b)
      hi = 0
      rem = b
      while rem >= 16
        rem = rem - 16
        hi = hi + 1
      end
      "%" + hex_char(hi) + hex_char(rem)
    end

    def self.hex_char(n)
      return n.to_s if n < 10
      return "A" if n == 10
      return "B" if n == 11
      return "C" if n == 12
      return "D" if n == 13
      return "E" if n == 14
      "F"
    end

    # Whether every plain literal segment of the pattern (no `:` or `*`)
    # equals the path's segment at the same index. Its own method for the
    # same reason as `glob_rest` below: one `while` per method.
    def self.literals_match(pattern_parts, path_parts)
      i = 0
      while i < pattern_parts.length
        pp = pattern_parts[i]
        ap = path_parts[i].to_s
        unless pp.include?(":") || pp.start_with?("*")
          return false if pp != ap
        end
        i += 1
      end
      true
    end

    # The path from segment `from` on, slash-joined: a `*glob`'s value.
    # Its own method rather than a loop inside `match_parts` because the
    # Elixir lowering turns ONE `while` per method into a recursive
    # `__loop`; a second, nested one is not a shape it takes.
    def self.glob_rest(path_parts, from)
      rest = []
      j = from
      while j < path_parts.length
        seg = path_parts[j]
        rest << seg
        j += 1
      end
      rest.join("/")
    end

    # Where the `:` of a prefixed param segment (`~:username`) sits —
    # the prefix's length; -1 when the segment has none. Its own method
    # for the same one-`while`-per-method reason as `glob_rest`.
    def self.param_prefix_length(segment)
      i = 0
      while i < segment.length
        return i if segment[i, 1].to_s == ":"
        i += 1
      end
      -1
    end

    # Is `name` one of the route's digit-constrained params?
    # `int_params` is the space-joined constraint list carried on
    # `Route`; the empty string means the route constrains nothing.
    # Membership by split + `==` scan (no `Array#include?`, no `Hash`
    # read) so it lowers cleanly to every target. Named without a `?`
    # suffix on purpose: the Elixir lowering appends `__loop` to a
    # while-loop method's own name, and `?` can only end an Elixir
    # identifier — `int_constrained?__loop` would fail to parse.
    def self.int_constrained(int_params, name)
      return false if int_params.empty?
      parts = int_params.split(" ")
      i = 0
      while i < parts.length
        return true if parts[i] == name
        i += 1
      end
      false
    end

    # All-digits check for constrained segments. No regex (the router
    # stays cross-target lowerable) and no `to_i` round-trip (it would
    # reject the leading zeros Roda's `Integer` matcher accepts —
    # `/articles/007` is id 7, not a 404). The digit test is an explicit
    # `String#==` fan-out rather than `"0123456789".include?(c)`: a
    # string *literal* receiver for `#include?` lowers to a struct call
    # on Elixir and an unsatisfiable `Pattern` bound on Rust, whereas
    # `==` against single-char literals is a proven strict-emitter shape.
    def self.digits_only(s)
      return false if s.empty?
      i = 0
      while i < s.length
        c = s[i, 1].to_s
        if c != "0" && c != "1" && c != "2" && c != "3" && c != "4" &&
           c != "5" && c != "6" && c != "7" && c != "8" && c != "9"
          return false
        end
        i += 1
      end
      true
    end
  end
end
